/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Redesign_UI;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
/*class ListNode{ //kelas objek ListNode yang berisi deklarasi variabel
        String key;     
        String value;   
        ListNode next;
      
    }*/
public class ListKata1English extends javax.swing.JFrame {
        private ListNode[] hashArray;
        private int count;
    /**
     * Creates new form ListKata
     */
    public ListKata1English() {
        hashArray=new ListNode[200];
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public String insert(String data){ //method untuk memasukkan kunci dan nilai
        int hashVal=hashFunc(data); //key yang dimasukkan akan diproses di hashFunc di dalam variabel hashval
        ListNode list=hashArray[hashVal]; //nilai dari hashVasl akan disimpan di hashArray dalam bentuk list 
        
       /* while(list !=null){ //jika list tidak bernilai null maka akan di looping
            if (list.key.equals(key)) { //jika list dari key objek sama dengan key yang dimasukkan 
                break; //maka di break
            }
            list=list.next; //kemuadian list akan di next
        }
        if (list != null) { //jika list tidak bernilai null
            list.value=value; //maka value objek dari list bernilai value yang di inputkan 
        }*/
       // else{   //jika tidak
            /*if (count >=0.75*hashArray.length) {    //jika count lebih dari 0,75*ukuran array
                resize();   //maka akan di resize
            }*/
            ListNode newNode=new ListNode(); //inisialisasi newnode dengan objek listnode baru
            newNode.key=data; //nilai key objek dari newnode bernilai key inputan 
            //newNode.value=value;    //dan nilai value obek dari newnode bernilai value inputan
            newNode.next=hashArray[hashVal];    
            hashArray[hashVal]=newNode;
            count++;
        //}
            return data;
    }
    public int hashFunc(String key){
        return (Math.abs(key.hashCode())) % hashArray.length;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        Tampilkata = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        ListWords = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 60, 60));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 40));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 60));

        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 50));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, 40));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 40, 40));

        Tampilkata.setBackground(new java.awt.Color(153, 153, 255));
        Tampilkata.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Tampilkata.setForeground(new java.awt.Color(102, 102, 102));
        Tampilkata.setText("Show the List");
        Tampilkata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkataActionPerformed(evt);
            }
        });
        getContentPane().add(Tampilkata, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 330, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("List 1 of 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 760, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 760, 90, -1));

        tabel.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kata", "Makna"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 560, 600));

        ListWords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menuwordList.png"))); // NOI18N
        getContentPane().add(ListWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TampilkataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkataActionPerformed
          DefaultTableModel dataModel = (DefaultTableModel) tabel.getModel();
          ListKata1English kata= new ListKata1English();
          
          tabel.setAutoCreateColumnsFromModel(true);
         dataModel.addRow(new Object[]{ 1,kata.insert("Application Binary Interface"),kata.insert("Exposure to hardware specifications and operating systems currently in use")});
         dataModel.addRow(new Object[]{ 2,kata.insert("Access"),kata.insert("Activities to retrieve or save data from or to the memory to the disk drive")});
         dataModel.addRow(new Object[]{ 3,kata.insert("Accessibillity"),kata.insert("How to set buttons, sounds, views and so on in Windows operating systems")});
         dataModel.addRow(new Object[]{ 4,kata.insert("Access Method"),kata.insert("Software that controls the transfer of data between the main storage and input and output equipment in a system")});
         dataModel.addRow(new Object[]{ 5,kata.insert("Access Time"),kata.insert("The time it takes to take or enter data from or to Memory")});
         dataModel.addRow(new Object[]{ 6,kata.insert("Accessories"),kata.insert("On Windows operating systems, accessories are programs such as Calculator, Notepad, Wordpad, Paint and so on. ")});
         dataModel.addRow(new Object[]{ 7,kata.insert("Accumulator"),kata.insert("Part of the arithmatic unit about a computer to store the results of a temporary calculation or some other operation.")});
         dataModel.addRow(new Object[]{ 8,kata.insert("Acknowledge"),kata.insert("Sign from the recipient terminal that the sending message has reached without any offense. Acknowledge comes from Acknowledgement words.")});
         dataModel.addRow(new Object[]{ 9,kata.insert("Accoustic Coupler"),kata.insert("A tool similar to a simple modem to send computer data through the telephone line. This tool converts binary signals into acoustic signals for acceptable phone microphones, the acoustic signal from the phone speakers will be converted into digital signals.")});
         dataModel.addRow(new Object[]{ 10,kata.insert("ACL"),kata.insert("(Access Control Unit) : The method to selectively restrict the use of a service is to make a list of services that can be accessed or that are not allowed by a particular host. ")});
         dataModel.addRow(new Object[]{ 11,kata.insert("ACPI"),kata.insert("(Advanced Configuration Power Interface) : A technology that allows the operating system to control the amount of electrical power used by each device installed on the computer.")});
         dataModel.addRow(new Object[]{ 12,kata.insert("Active Task Button"),kata.insert("A command button located on the taskbar that will appear if a command must be executed.")});
         dataModel.addRow(new Object[]{ 13,kata.insert("Active"),kata.insert("Everything that relates to every tool or system is currently in use.")});
         dataModel.addRow(new Object[]{ 14,kata.insert("ActiveX"),kata.insert("The programming environment performed by Microsoft to create an active system on Web pages, which also supports Java, JavaScript, Visual Basic and other programming languages that are all limited and can only be used in Internet Explorer.")});
         dataModel.addRow(new Object[]{ 15,kata.insert("ADC"),kata.insert("(Analog/Digital Converter) : The tool used to convert the analog signal into a digital signal.")});
         dataModel.addRow(new Object[]{ 16,kata.insert("Add-in"),kata.insert("Additional equipment paired to one of the available boards. Supporting programs are added to an application program.")});
         dataModel.addRow(new Object[]{ 17,kata.insert("Address"),kata.insert("The numbers that indicate the location in the memory as the place of information is stored.")});
         dataModel.addRow(new Object[]{ 18,kata.insert("Adobe PageMaker"),kata.insert("Application software that processes data for the needs of creation of book layout design, cover for magazines, newspapers, etc. Usually used by the type of computer setting business for the purpose of making invitation cards, business cards, greeting cards, letterhead, and so forth.")});
         dataModel.addRow(new Object[]{ 19,kata.insert("Adobe Photoshop"),kata.insert("Application software that processes image and graphics data for printing needs, graphic design.")});
         dataModel.addRow(new Object[]{ 20,kata.insert("ADSL"),kata.insert("(Asymmetric Digital Subscriber Lines) : High-level digital data delivery above the line of the phone.")});
         dataModel.addRow(new Object[]{ 21,kata.insert("Advertiser"),kata.insert("The same means with merchants, i.e. merchants or companies that give commissions.")});
         dataModel.addRow(new Object[]{ 22,kata.insert("Affiliate Site"),kata.insert("Pages where merchant ads are included. We can insert a merchant ad into any page on the website, and the location can be checked in place.")});
         dataModel.addRow(new Object[]{ 23,kata.insert("AGP"),kata.insert("(Accelerated Graphics Port) : A high-speed graphics bus that directly connects a graphics card with the main memory. AGP operates independently and separately with PCI buses and generally runs at 66MHz i.e. twice the PCI speed running at 33MHz. AGP 1x performs one-time transfer per working cycle to perform maximum data transfer of 266 MB per second. AGP 2x performs twice the transfer of data per one work cycle of 533 MB per second while AGP 4x performs four times the transfer per one work cycle of 1.06 GB per second. While the maximum data transfer rate on PCI is 132 MB per second.")});
         dataModel.addRow(new Object[]{ 24,kata.insert("AI"),kata.insert("(Artificial Intelligence) : The science that develops the computer so that it can work and think and make decisions like human beings.")});
         dataModel.addRow(new Object[]{ 25,kata.insert("ALGOL"),kata.insert("(Algortihmic Oriented Language) : A high-level programming language used to resolve issues in limited measures. Generally to make science programs")});
         dataModel.addRow(new Object[]{ 26,kata.insert("Aligment"),kata.insert("In computer networks is the process of leveling the components of a system against other components. For example synchronize computer time from a system.")});
         dataModel.addRow(new Object[]{ 27,kata.insert("Align"),kata.insert("From the word alignment, that is, the command in a word processing program to flatten a script, whether left, right, or center align.")});
         dataModel.addRow(new Object[]{ 28,kata.insert("Allocate"),kata.insert("Instructions for putting a portion of the computer's memory or other units under computer program control.")});
         dataModel.addRow(new Object[]{ 29,kata.insert("Alpha Numeric"),kata.insert("A mixture of characters and numbers including letters (A-Z; A-Z), punctuation marks and some special characters e.g. @, #, $, *, etc.")});
         dataModel.addRow(new Object[]{ 30,kata.insert("Alias"),kata.insert("The second name of a file, generally the second name is shorter and easier to remember than the first name.")});
         dataModel.addRow(new Object[]{ 31,kata.insert("ALOHA"),kata.insert("Intermediate level access surveillance technique for transmission media that handles a lot of access. Data transmission will be done at any time by a station. The shipment will be repeated when you get NAK response (there is a shipment error) from the destination station.")});
         dataModel.addRow(new Object[]{ 32,kata.insert("Alt Key"),kata.insert("The button name on the keyboard is located to the right and left of the space bar. This new button works when pressed together with another key. In Windows environment, this button along with certain letters can be used to quickly open and select commands on the menu.")});
         dataModel.addRow(new Object[]{ 33,kata.insert("ALU"),kata.insert("(Arithmetic and Logical Unit) :The part of the CPU is useful for processing the data logically and also the data that requires calculations. ALU consists of a register-register to store information.")});
         dataModel.addRow(new Object[]{ 34,kata.insert("AMD760"),kata.insert("The AMD760 chipset is an AMD chipset for Athlon processors.")});
         dataModel.addRow(new Object[]{ 35,kata.insert("Analog"),kata.insert("The form of electronic communication that uses continuous electromagnetic waves, such as television and radio.")});
         dataModel.addRow(new Object[]{ 36,kata.insert("Analog Sinyal"),kata.insert("The continuous electromagnetic waves, having the ability to be transmitted through various media and the range is much larger than the digital signal")});
         dataModel.addRow(new Object[]{ 37,kata.insert("AND"),kata.insert("One of the logical operators of the Boolean algebra to compare whether two variables would produce the correct value (1) or False (0)")});
         dataModel.addRow(new Object[]{ 38,kata.insert("Anti Virus"),kata.insert("A Program created specifically to detect files in a drive is exposed to viruses or not. This Program also removes the virus.")});
         dataModel.addRow(new Object[]{ 39,kata.insert("Application Program"),kata.insert("Computer programs are created to work on or solve specific problems, such as payroll programs.")});
         dataModel.addRow(new Object[]{ 40,kata.insert("ARPANET"),kata.insert("The computer network developed with the help of the Advanced Research Project Agency, is the forerunner of the Internet.")});
         dataModel.addRow(new Object[]{ 41,kata.insert("Assembler"),kata.insert("Program that serves to convert the program with the Assembly language into the machine language.")});
         dataModel.addRow(new Object[]{ 42,kata.insert("Assembly"),kata.insert("The translation process of the program is written with the symbol programming language into the machine language.")});
         dataModel.addRow(new Object[]{ 43,kata.insert("Assembly Language"),kata.insert("A low-level programming language that resembles a machine language in a memorable form.")});
         dataModel.addRow(new Object[]{ 44,kata.insert("Background"),kata.insert("Colors or drawings are arranged to create a background effect within a webpage.")});
         dataModel.addRow(new Object[]{ 45,kata.insert("Backplane"),kata.insert("a board to which the main circuit boards of a computer may be connected, and which provides connections between them.")});
         dataModel.addRow(new Object[]{ 46,kata.insert("Backspace"),kata.insert("The keyboard button is located above the Enter key. Function to delete the character saut before the current cursor.")});
         dataModel.addRow(new Object[]{ 47,kata.insert("Backup"),kata.insert("A copy of the program file or data file is created to guarantee that the existing data is not lost or deleted if something happens to the original file.")});
         dataModel.addRow(new Object[]{ 48,kata.insert("Bandwith"),kata.insert("The capacity of transmsides of electronic connections such as communication networks, I bus computers and computer channels. Usual denoted by bits per second or Hertz. ")});
         dataModel.addRow(new Object[]{ 49,kata.insert("Banner"),kata.insert("The parts are not moving in the Web document even though we rolled the the is to the end of the document. Now this is only Ineternet Explorer that supports command banners.")});
         dataModel.addRow(new Object[]{ 50,kata.insert("Bar Code"),kata.insert("Numeric characters are displayed in the form of beams with varying thickness.")});
         dataModel.addRow(new Object[]{ 51,kata.insert("Baterai CMOS"),kata.insert("This battery serves to power the motherboard in recognizing the configuration installed, when it is not or not yet get power from the power supply.")});
         dataModel.addRow(new Object[]{ 52,kata.insert("Baud"),kata.insert("The Signal speed unit is Digita, the limit used to indicate the level of data transmission speed. Typically calculated in bits per second.")});
         dataModel.addRow(new Object[]{ 53,kata.insert("Binary"),kata.insert("The numbering system used by the computer consists of only two digits, namely 1 and 0. This is due to the electronic circuits that the computer uses only have two statuses on and off.")});
         dataModel.addRow(new Object[]{ 54,kata.insert("BIOS"),kata.insert("Basic Input Output System) : 1. Part of the operating system that can identify the set of programs used to boot the computer, before placing the system diskette. The BIOS is in ROM (Read Only Memory) of the system and is generally permanently stored. 2. Program used microprocessors to start the computer. The BIOS also regulates the flow of data between the computer operating system and enhancements connected to the computer.")});
         dataModel.addRow(new Object[]{ 55,kata.insert("Bipolar"),kata.insert("Refers to a regular transistor or IC as opposed to the MOS and CMOS components.")});
         dataModel.addRow(new Object[]{ 56,kata.insert("Bit"),kata.insert("The smallest Unit of information. One bit is enough to declare the difference between yes and no, top and bottom, on and off, one and zero. The computer should display the information in bits because the electronic circuits created only have two circumstances, on or off.")});
         dataModel.addRow(new Object[]{ 57,kata.insert("Black Box"),kata.insert("A tool or a process that is specific only within the limits of the input and output process. We do not know what is happening inside.")});
         dataModel.addRow(new Object[]{ 58,kata.insert("Black Hat"),kata.insert("Malicious hacker, Black Hat Hacker is also commonly referred to as \"aka crackers\" with the ability to steal data or damage the system that exists in the victim's computer. The advantage of Black hat is the ability to eliminate traces until it is not trackable who actually perpetrators of attacks that occur after their specific objectives are fulfilled.")});
         dataModel.addRow(new Object[]{ 59,kata.insert("Bluetooth"),kata.insert("Technology created for close-up wireless connections (RADIUS 10 meters). This technology uses transceiver chips that are assembled on mobile computers, phones, and other portable equipment")});
         dataModel.addRow(new Object[]{ 60,kata.insert("Brainware"),kata.insert("Term to declare human being a computer user. Brainware can be categorized into a system of analysts, programmers and operators.")});
         dataModel.addRow(new Object[]{ 61,kata.insert("Break"),kata.insert("Command to stop the program. Usually this command is done by cutting the CTRL + C key.")});
         dataModel.addRow(new Object[]{ 62,kata.insert("Break Point"),kata.insert("Some computers have a switch that will make the computer stop at a certain point in the program, so the operator can inspect the program's path; Or can also by way of placing stop orders in the program. This command can be deleted if the program has been running properly.")});
         dataModel.addRow(new Object[]{ 63,kata.insert("Buffer"),kata.insert("Temporary data storage place. It is often used when data transmission should take place at different speeds")});
         dataModel.addRow(new Object[]{ 64,kata.insert("Bridge"),kata.insert("Devices that connect the network physically by holding two LANS using similar protocols")});
         dataModel.addRow(new Object[]{ 65,kata.insert("Broadcast"),kata.insert("Delivery of messages to all points in a network.")});
         dataModel.addRow(new Object[]{ 66,kata.insert("Browse"),kata.insert("Commands in Windows environment to display disk contents. Application Program used for browsing.")});
         dataModel.addRow(new Object[]{ 67,kata.insert("Browsing"),kata.insert("Multiple site browsing activity on the Internet.")});
         dataModel.addRow(new Object[]{ 68,kata.insert("Bytes"),kata.insert("Information with a length of 8 bits.")});
         dataModel.addRow(new Object[]{ 69,kata.insert("BYTE Mode"),kata.insert("The data delivery Model is done by transferring bytes by Byte.")});
         dataModel.addRow(new Object[]{ 70,kata.insert("Cache"),kata.insert("Derived from the word cash, used to increase data transfer speeds either temporarily or permanently.")});
         dataModel.addRow(new Object[]{ 71,kata.insert("Cancel"),kata.insert("Used to cancel the order or foil the activity in progress.")});
         dataModel.addRow(new Object[]{ 72,kata.insert("CAPS Lock"),kata.insert("A button on the keyboard that works converts all the letter keys to uppercase.")});
         dataModel.addRow(new Object[]{ 73,kata.insert("Caption"),kata.insert("In an Ms-Word word processing environment This command is used to add captions to an image, table or other object.")});
         dataModel.addRow(new Object[]{ 74,kata.insert("Catalog"),kata.insert("The command in DOS to display a list of files that are in a disk.")});
         dataModel.addRow(new Object[]{ 75,kata.insert("CD"),kata.insert("(Carrier Detect) Modem Status If it is connected with another modem.")});
         dataModel.addRow(new Object[]{ 76,kata.insert("CD Drive"),kata.insert("(Drive CD)  A drive to record or play Compact Disk, which is often encountered are CD-ROMS (DISC Read Only Memory) MO (Magneto-Optical) and WORM (Write Once Read Many).")});
         dataModel.addRow(new Object[]{ 77,kata.insert("CD ROM"),kata.insert("(Compact Disc Read Only Memory) : Compact Disk that cannot be used for rewriting (removed or added); Used in computer data storage.")});
         dataModel.addRow(new Object[]{ 78,kata.insert("CD RW"),kata.insert("A Compact Disk that, in addition to being readable, can also be used to store data by writing it using the CD-RW Drive")});
         dataModel.addRow(new Object[]{ 79,kata.insert("CD Title"),kata.insert("Compact Disc that contains computer programs.")});
         dataModel.addRow(new Object[]{ 80,kata.insert("CDMA"),kata.insert("(Code Division Multiple Access) : Air-spectrum spread interface technology used on some phones and other wireless networks.")});
         dataModel.addRow(new Object[]{ 81,kata.insert("Chace"),kata.insert("Mentions for graphics cards such as VGA card.")});
         dataModel.addRow(new Object[]{ 82,kata.insert("Chaining"),kata.insert("The working process of the computer is connected in a series of segments. If a program is too large in memory, the program should be written in several segments. The computer will work in one segment at any one time until completion, the result will be taken to the next segment. So on until the program finishes processing.")});
         dataModel.addRow(new Object[]{ 83,kata.insert("Channel"),kata.insert("Channels to transmit electromagnetic signals capable of connecting the CPU with other equipment.")});
         dataModel.addRow(new Object[]{ 84,kata.insert("Chat"),kata.insert("Online conversation services commonly used by Internet users to talk to other users")});
         dataModel.addRow(new Object[]{ 85,kata.insert("CHDIR"),kata.insert("Command to move or activate the directory in the DOS operating system environment.")});
         dataModel.addRow(new Object[]{ 86,kata.insert("CHIP"),kata.insert("Small bits of silicon are the essence of an IC (Integrated Circuit) or a designation for IC.")});
         dataModel.addRow(new Object[]{ 87,kata.insert("Chipset"),kata.insert("Chips or chipsets are small pieces of silicon used to store information and computer instruction. Each computer component has at least a chip in it. The Chipset on the motherboard controls the basic input and output (inputs and outputs) of the computer. The Chipset on the video card controls the rendering of the 3D graphics and outputs of the image on your monitor. CPU is one of the very important chip examples. Chipset motherboard eg BX, i810, i820, and many others.")});
         dataModel.addRow(new Object[]{ 88,kata.insert("Circuit Board"),kata.insert("A circuit board complete with electronic components that are placed and soldered in place.")});
         dataModel.addRow(new Object[]{ 89,kata.insert("Click"),kata.insert("Terms to represent the selection of objects or menus by pressing one mouse button.")});
         dataModel.addRow(new Object[]{ 90,kata.insert("Client"),kata.insert("On the network, a client is an application software that allows users to access service or services from a server computer.")});
         dataModel.addRow(new Object[]{ 91,kata.insert("Client-Server"),kata.insert("A form of architecture where the client is a receiving device that will display the user interface and run applications (computers) and servers is a device that provides and acts as an application manager, data and security (server or mainframe).")});
         dataModel.addRow(new Object[]{ 92,kata.insert("Data"),kata.insert("A collection of numbers and characters that have no meaning. Data can be processed, resulting in information.")});
         dataModel.addRow(new Object[]{ 93,kata.insert("Database"),kata.insert("A bunch of interrelated files and forming a data build up. The minimal Database consists of a single file enough to be manipulated by the computer in such a way.")});
         dataModel.addRow(new Object[]{ 94,kata.insert("Database Administrator"),kata.insert("The person in charge of defining the pattern of the database structure, specifying the access and storage methods, is authorized to permit accessing the data on the user, and so forth.")});
         dataModel.addRow(new Object[]{ 95,kata.insert("Database Information Utility"),kata.insert("Database Information Utility")});
         dataModel.addRow(new Object[]{ 96,kata.insert("Database Management"),kata.insert("Data management in a database, how to enter the data in databases, renew it and present information from that data.")});
         dataModel.addRow(new Object[]{ 97,kata.insert("Decision Support System"),kata.insert("One computer-based information system that presents information specifically for management to support decision making.")});
         dataModel.addRow(new Object[]{ 98,kata.insert("Declaration"),kata.insert("The process of introducing a variable data type to the compiler will therefore be known how much memory to set up for each variable.")});
         dataModel.addRow(new Object[]{ 99,kata.insert("DECnet"),kata.insert("A group of network protocols created by Digital Equipment Corporation that are specifically used on DEC's computers to communicate.")});
         dataModel.addRow(new Object[]{ 100,kata.insert("DECNET"),kata.insert("Special networking Software for digital computers similar to OSI. DECNET has the ability to be part of a network that uses standard X. 25 or IBM SNA.")});
          // TODO add your handling code here:
    }//GEN-LAST:event_TampilkataActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(EXIT_ON_CLOSE); // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new MenuEnglish().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new HomePage().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new MenuEnglish().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ListKata2English().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new AboutEnglish().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListKata1English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListKata1English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListKata1English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListKata1English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListKata1English().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel ListWords;
    private javax.swing.JButton Tampilkata;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
