/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Redesign_UI;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
/*class ListNode{ //kelas objek ListNode yang berisi deklarasi variabel
        String key;     
        String value;   
        ListNode next;
      
    }*/
public class ListKata2English extends javax.swing.JFrame {
        private ListNode[] hashArray;
        private int count;
    /**
     * Creates new form ListKata
     */
    public ListKata2English() {
        hashArray=new ListNode[200];
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public String insert(String data){ //method untuk memasukkan kunci dan nilai
        int hashVal=hashFunc(data); //key yang dimasukkan akan diproses di hashFunc di dalam variabel hashval
        ListNode list=hashArray[hashVal]; //nilai dari hashVasl akan disimpan di hashArray dalam bentuk list 
        
       /* while(list !=null){ //jika list tidak bernilai null maka akan di looping
            if (list.key.equals(key)) { //jika list dari key objek sama dengan key yang dimasukkan 
                break; //maka di break
            }
            list=list.next; //kemuadian list akan di next
        }
        if (list != null) { //jika list tidak bernilai null
            list.value=value; //maka value objek dari list bernilai value yang di inputkan 
        }*/
       // else{   //jika tidak
            /*if (count >=0.75*hashArray.length) {    //jika count lebih dari 0,75*ukuran array
                resize();   //maka akan di resize
            }*/
            ListNode newNode=new ListNode(); //inisialisasi newnode dengan objek listnode baru
            newNode.key=data; //nilai key objek dari newnode bernilai key inputan 
            //newNode.value=value;    //dan nilai value obek dari newnode bernilai value inputan
            newNode.next=hashArray[hashVal];    
            hashArray[hashVal]=newNode;
            count++;
        //}
            return data;
    }
    public int hashFunc(String key){
        return (Math.abs(key.hashCode())) % hashArray.length;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        Tampilkata = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 60, 60));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 40));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 60));

        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 50));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, 40));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 40, 40));

        Tampilkata.setBackground(new java.awt.Color(153, 153, 255));
        Tampilkata.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Tampilkata.setForeground(new java.awt.Color(102, 102, 102));
        Tampilkata.setText("Show the List");
        Tampilkata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkataActionPerformed(evt);
            }
        });
        getContentPane().add(Tampilkata, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 330, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("List 2 of 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 760, -1, -1));

        tabel.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kata", "Makna"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 560, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menuwordList.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TampilkataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkataActionPerformed
          DefaultTableModel dataModel = (DefaultTableModel) tabel.getModel();
          ListKata2English kata= new ListKata2English();
          
          tabel.setAutoCreateColumnsFromModel(true);
         dataModel.addRow(new Object[]{ 101, kata.insert("DECnet/OSI"),kata.insert("The DECnet protocol is compatible with phase V Digital Network Architecture (DNA) products. This Protocol supports an OSI open system.")});
         dataModel.addRow(new Object[]{ 102, kata.insert("Decreament"),kata.insert("To reduce the value of a variable one by one.")});
         dataModel.addRow(new Object[]{ 103, kata.insert("Decompress"),kata.insert("Restores the compressed files to their original state of the file.")});
         dataModel.addRow(new Object[]{ 104, kata.insert("Default"),kata.insert("Fixed tuning results for running a program or application")});
         dataModel.addRow(new Object[]{ 105, kata.insert("Demodulation"),kata.insert("The process of converting analogue signals into digital form.")});
         dataModel.addRow(new Object[]{ 106, kata.insert("Desktop"),kata.insert("One computer packaging model that was deliberately designed to be placed on a working desk.")});
         dataModel.addRow(new Object[]{ 107, kata.insert("Desktop Publishing"),kata.insert("The Software is used to create and manage formats on magazine and book printing easily. Examples of DTP software are Ventura and Pagemaker.")});
         dataModel.addRow(new Object[]{ 108, kata.insert("Dial"),kata.insert("The process of connecting a computer to a station or an Internet address through a communication channel.")});
         dataModel.addRow(new Object[]{ 109, kata.insert("Dial Line"),kata.insert("Another term to mention the Channel liaison (switch connection).")});
         dataModel.addRow(new Object[]{ 110, kata.insert("Dial Up"),kata.insert("A type of communication that uses a modem and a regular telephone line to be able to connect between computers with another computer, or it can also mean an Internet provider that utilizes the phone line as its main channel. This relationship is only temporary.")});
         dataModel.addRow(new Object[]{ 111, kata.insert("Dial Up Line"),kata.insert("Communication line used on dial up process, especially general network or ordinary telephone network.")});
         dataModel.addRow(new Object[]{ 112, kata.insert("DIR"),kata.insert("In DOS operating system means the command to display the list of all files in the active disk to the screen.")});
         dataModel.addRow(new Object[]{ 113, kata.insert("Dial Up Terminal"),kata.insert("A terminal on the shifting channel.")});
         dataModel.addRow(new Object[]{ 114, kata.insert("Disconnect"),kata.insert("The term to declare a disconnection with the communication channel or the state is not connected to any network.")});
         dataModel.addRow(new Object[]{ 115, kata.insert("Disconnect time-out"),kata.insert("The deadline used by switched networks to perform termination of communication if a station is inactive exceeds the deadline.")});
         dataModel.addRow(new Object[]{ 116, kata.insert("Discreate Circuitry"),kata.insert("Build electronic circuits by attaching multiple parts individually. The inverse of IC, and currently discreate circuitry is rarely used because it is expensive and less reliable.")});
         dataModel.addRow(new Object[]{ 117, kata.insert("Disk"),kata.insert("Thin disc coated with magnetic material (iron oxide) capable of storing a certain amount of data or information. Reading and writing information is centered on the track.")});
         dataModel.addRow(new Object[]{ 118, kata.insert("Disk Cleaner"),kata.insert("Diskette that cleans the head of a disk drive")});
         dataModel.addRow(new Object[]{ 119, kata.insert("Diskcopy"),kata.insert("Program under DOS that serves to copy the entire contents of a disk with the same type of drive.")});
         dataModel.addRow(new Object[]{ 120, kata.insert("Disk Drive"),kata.insert("An additional tool is used to place the magnetic disc, rotate the disc and move the read/write head at the desired position when accessing the information from within the disk")});
         dataModel.addRow(new Object[]{ 121, kata.insert("Diskette"),kata.insert("The magnetic disc is thin, flexible and wrapped in a box-shaped packaging of plastic material, used to store a certain amount of data/information. The floppy is generally 31/2 inches.")});
         dataModel.addRow(new Object[]{ 122, kata.insert("Display"),kata.insert("Hardware that presents the results of computer output in visual form.")});
         dataModel.addRow(new Object[]{ 123, kata.insert("Documentation"),kata.insert("Documentation that stores the written description of a program including the program name, program functions, required inputs/outputs, is likely written in the algorithm, how the data structure, and so on.")});
         dataModel.addRow(new Object[]{ 124, kata.insert("Domain"),kata.insert(": The definition of an address on the Internet, which also refers to a country where the website is used. For example co.id for Indonesia. While co or COM for commercial institutions and net for Internet-related agencies.")});
         dataModel.addRow(new Object[]{ 125, kata.insert("Domain Name"),kata.insert(": Part of the URL or site address indicating ownership, e.g. andinomaseleno.com indicates the address is owned by Andinomaseleno.")});
         dataModel.addRow(new Object[]{ 126, kata.insert("Drag"),kata.insert("Terms that illustrate the activity of moving the mouse while still holding the mouse button")});
         dataModel.addRow(new Object[]{ 127, kata.insert("Drag and Drop"),kata.insert("The term describing the activity selects an object and moves the mouse to a new location while still pressing the left mouse button (drag), then placing the object at that location (drop).")});
         dataModel.addRow(new Object[]{ 128, kata.insert("Duplex"),kata.insert("1. Communication lines capable of sending two-way data. 2. Computer system that uses 2 interconnected CPUS.")});
         dataModel.addRow(new Object[]{ 129, kata.insert("Duplexed System"),kata.insert("The data communication environment is a system that has two different tools and does not affect each other. Each tool is capable of carrying out its functions; It is possible that one of the tools will be considered a backup.")});
         dataModel.addRow(new Object[]{ 130, kata.insert("EFT"),kata.insert("(Electronic Funds Transfer) : The engineering of electronic data transfer or exchange of financial transactions.")});
         dataModel.addRow(new Object[]{ 131, kata.insert("Eject"),kata.insert(": The command is given on the printer to place the paper at the beginning of the page. If the paper position is in the middle, the rest of the page will be ignored and put the next paper at the beginning of the page.")});
         dataModel.addRow(new Object[]{ 132, kata.insert("E-mail"),kata.insert(": Internet correspondence. Users can exchange news. The news will be collected in a file for mailbox addressing, so that the user can read the news addressed to him at any time.")});
         dataModel.addRow(new Object[]{ 133, kata.insert("E-mail Address"),kata.insert("address used in the e-mail delivery process to the destination. The address is based on DNS.")});
         dataModel.addRow(new Object[]{ 134, kata.insert("Encode"),kata.insert(": The activity prepares a program routine into the machine language so that it can be immediately implemented by the computer.")});
         dataModel.addRow(new Object[]{ 135, kata.insert("Encoder"),kata.insert(": A computer system or network system capable of receiving only one input, each input will generate several combinations of output results.")});
         dataModel.addRow(new Object[]{ 136, kata.insert("Encryption"),kata.insert("Translating data into secret codes. Encryption is the most effective way to gain data security. To read the encrypted file, we need to have access to a password that allows us to decrypt the message. Unencapsulation Data is called Plain text, while the ones that are encapsulation are  called cipher text.")});
         dataModel.addRow(new Object[]{ 137, kata.insert("End"),kata.insert(": Keys on the keyboard, serve to move the cursor to the end of the line.")});
         dataModel.addRow(new Object[]{ 138, kata.insert("Error"),kata.insert("The term to indicate that there is a deviation in software or hardware malfunction")});
         dataModel.addRow(new Object[]{ 139, kata.insert("Ethernet"),kata.insert("A standard LAN includes cable and communication protocol schemes developed by Xerox Corporation. Now Ethernet is a protocol that is widely used and adapted by other companies.")});
         dataModel.addRow(new Object[]{ 140, kata.insert("Ethernet Cabel"),kata.insert("All media cables for the Ethernet network. Example of Ethernet cable is type cable 10base5, UTP/STP")});
         dataModel.addRow(new Object[]{ 141, kata.insert("Ether Talk"),kata.insert("The encapsulated AppleTalk packages that are passed on the Ethernet cable.")});
         dataModel.addRow(new Object[]{ 142, kata.insert("Eudora"),kata.insert("The E-mail Service Application Program on the Internet. Facsimile: The sender tool of the document or the image from one place to another by using the telephone line. Delivery can be done if the sender and receiver both activate this machine.")});
         dataModel.addRow(new Object[]{ 143, kata.insert("Fading"),kata.insert("Disruption of transmission lines, especially in the microwave system when signals sent through various lines to the receiver are changed due to atmospheric conditions")});
         dataModel.addRow(new Object[]{ 144, kata.insert("Failure"),kata.insert("A statement indicating that the related tool is not running properly.")});
         dataModel.addRow(new Object[]{ 145, kata.insert("Female Connector"),kata.insert("A plug or socket that has a receptacles. The opponent is a \"man connector\" that has a pin")});
         dataModel.addRow(new Object[]{ 146, kata.insert("Fetch"),kata.insert("Software Program to move files developed by Dartmouth College for Macintosh. The Program provides access to a user friendly FTP.")});
         dataModel.addRow(new Object[]{ 147, kata.insert("File"),kata.insert("The File consists of a set of interconnected records. Each record has a number that is adjusted to its position in the file.")});
         dataModel.addRow(new Object[]{ 148, kata.insert("Folder"),kata.insert("In a Graphical User Interface (GUI) environment such as Windows and Macintosh, a folder is an object that can contain multiple documents. Folders are used to organize information. On DOS and UNIX, the folder is called Directory (directory).")});
         dataModel.addRow(new Object[]{ 149, kata.insert("giganinta"),kata.insert("In a Graphical User Interface (GUI) environment such as Windows and Macintosh, a folder is an object that can contain multiple documents. Folders are used to organize information. On DOS and UNIX, the folder is called Directory (directory).")});
         dataModel.addRow(new Object[]{ 150, kata.insert("Gigabyte"),kata.insert("A term to mention an image that has a gray color, a.k.a. black and white. Greyscale represents the number of colors (from Gray, to black – white) that are in a single image. The bigger the Grayscale figure, the formed image is closer to reality.")});
         dataModel.addRow(new Object[]{ 151, kata.insert("Gigacycle"),kata.insert("Unit of frequency measure with 1 Gigacycle = 1 billion Hertz.")});
         dataModel.addRow(new Object[]{ 152, kata.insert("Google"),kata.insert ("Name of search engine on Internet.")});
         dataModel.addRow(new Object[]{ 153, kata.insert("Glossary"),kata.insert("The following glossary describes the meaning of the terms.")});
         dataModel.addRow(new Object[]{ 154, kata.insert("Gopher"),kata.insert("A menu-based information system on the Internet is popular for its ability to relate to other gopher sites in the same menu.")});
         dataModel.addRow(new Object[]{ 155, kata.insert("GPRS"),kata.insert("General Packet Radio Service )" +"Package-based communication services, wirelessly as a communication medium. This service is for portable computers (notebooks). The basis of GPRS is GSM (Global System for Mobile Communication) communication. The speeds offered range from 56 Kbps to 114 Kbps, allowing for faster access to the Internet.")});
         dataModel.addRow(new Object[]{ 156, kata.insert("GSM"),kata.insert("Global System for Mobile Communication) : sek Cellular digital or PCS standards used around the world. GSM is the most widely used standard in Europe and southeast Asia.")});
         dataModel.addRow(new Object[]{ 157, kata.insert("Guestbook"),kata.insert("Interactive facilities in a webpage that allow visitors to write messages.")});
         dataModel.addRow(new Object[]{ 158, kata.insert("Homepage"),kata.insert("The first page of a Web Site.")});
         dataModel.addRow(new Object[]{ 159, kata.insert("Host"),kata.insert("A term used to designate a computer that allows its users to connect to the Internet.")});
         dataModel.addRow(new Object[]{ 160, kata.insert("Host Name"),kata.insert("The name of the computer within the Internet, is used to indicate the URL naming scheme.")});
         dataModel.addRow(new Object[]{ 161, kata.insert("HTTP (Hyper Text Transfer Protocol"),kata.insert("A method or protocol to download files to a computer. This protocol is based on hyper text, a text format commonly used on the Internet.")});
         dataModel.addRow(new Object[]{ 162, kata.insert("Icon"),kata.insert("Interlaced GIP : A special GIF type that allows the display of the image to be displayed little by little when a webpage is being downloaded.")});
         dataModel.addRow(new Object[]{ 163, kata.insert("Internet"),kata.insert("A general term used to designate a world-wide Network consisting of computers and service services or about 30 to 50 million computer users and dozens of information systems including e-mail, Gopher, FTP and the World Wide Web.")});
         dataModel.addRow(new Object[]{ 164, kata.insert("Internet Device"),kata.insert("Advanced tools such as computers used to be able to communicate or interact through the Internet, whether to surf, send and receive e-mails, even to chat, using text, sound, images or video, for example: Notebook, palmtop, handphone, Internet-TV.")});
         dataModel.addRow(new Object[]{ 165, kata.insert("Internet Explorer"),kata.insert("A well-known free Web browser produced by Microsoft.")});
         dataModel.addRow(new Object[]{ 166, kata.insert("Intranet"),kata.insert("Information resources are used for the internal interests of an agency or company using an existing computer network.")});
         dataModel.addRow(new Object[]{ 167, kata.insert("Java"),kata.insert("he programming language to create active content within a Web page, can also be run on all computers. Java applets are retrieved/accessed from Web pages and run in total.")});
         dataModel.addRow(new Object[]{ 168, kata.insert("JavaScript"),kata.insert("Language script interpreter to create an active content in a Web page.")});
         dataModel.addRow(new Object[]{ 169, kata.insert("JPEG"),kata.insert(" (Joint Photographic Expert Group File formats that contain data in the form of images. JPEG images are compressed in lossy, so the image quality is lowered to obtain a small file size. However, the difference in quality will not be noticeable for certain images. JPEG is usually used for images of obscure color boundaries, such as photos, paintings, etc.")});
         dataModel.addRow(new Object[]{ 170, kata.insert("Kbps"),kata.insert("The unit of byte is equal to 1000 bits per second.")});
         dataModel.addRow(new Object[]{ 171, kata.insert("KHz"),kata.insert("The unit of frequency is equal to 1000 cycles per second.")});
         dataModel.addRow(new Object[]{ 172, kata.insert("Konektor Power"),kata.insert("Pin that connects the motherboard with the power supply in the case of a computer. On the AT type motherboard, the casing required is an AT type as well. The Type AT Power connectorconsists of two parts, where two cables from the power supply will be stuck. In the ATX type, the power supply cable is integrated into one intact header so that it stays on the motherboard. This cable consists of two columns according to the PIN on the motherboard consisting of two arrays of pins as well. There are several motherboards that provide two types of power, AT and ATX connectors. Most new motherboards already have ATX type.")});
         dataModel.addRow(new Object[]{ 173, kata.insert("LAN"),kata.insert("A network that is built on a location like at home or office buildings. It can also be interpreted as a computer communication system that is limited to no more than a few kilometers and uses a high-speed connection between 2 and 100 Mbps.")});
         dataModel.addRow(new Object[]{ 174, kata.insert("Layer"),kata.insert("Layer (concept) in networking. Various communication models such as OSI and TCP/IP consist of several layers that compose the protocol.")});
         dataModel.addRow(new Object[]{ 175, kata.insert("LCD (Liquid Crystal Display)"),kata.insert("The type of screen display using liquid compounding that has a polar molecular structure, flanked between two transparent electrodes. When the electric field is given, the molecule adjusts its position on the terrain, forming a crystalline arrangement that polarizes light through it.")});
         dataModel.addRow(new Object[]{ 176, kata.insert("LED (Light Emitting Diode)"),kata.insert("A small lamp is used as a marker or pointer.")});
         dataModel.addRow(new Object[]{ 177, kata.insert("Link"),kata.insert("Connection or connection from a source to another source. For example in networking or Internet systems.")});
         dataModel.addRow(new Object[]{ 178, kata.insert("Listsery"),kata.insert("Mailing list management Software.")});
         dataModel.addRow(new Object[]{ 179, kata.insert("Load Time"),kata.insert("The time it takes to fetch/open a web page on the computer.")});
         dataModel.addRow(new Object[]{ 180, kata.insert("Locate"),kata.insert("Commands are used in Linux/Unix to obtain certain files. Only the locate command should be preceded by slocate to do updating the file information within that host.")});
         dataModel.addRow(new Object[]{ 181, kata.insert("Localhost"),kata.insert("In the Networking world, Localhost is the term used for the host itself. The name localhost is used for the application configuration before actually getting the hostname of its hostmaster.")});
         dataModel.addRow(new Object[]{ 182, kata.insert("Log"),kata.insert("Records that record all activities of an application are executed. Sometimes Log is also used to analyze the status of an application.")});
         dataModel.addRow(new Object[]{ 183, kata.insert("Login"),kata.insert("The process to enter into a servicesonline containing the name and password")});
         dataModel.addRow(new Object[]{ 184, kata.insert("Logout"),kata.insert("Exit or close, the same means by signing out. Multiuser Systemany computer system that can be used by more than one person.")});
         dataModel.addRow(new Object[]{ 185, kata.insert("Modem"),kata.insert("Short for modulator/demodulator; Communication tool that allows the computer to transmit information through the standard telephone line")});
         dataModel.addRow(new Object[]{ 186, kata.insert("Motherboard"),kata.insert("The largest component in the PC. Called ' mother ' because this board is home to all PC components such as processors, main memory, support networks and bus controllers.")});
         dataModel.addRow(new Object[]{ 187, kata.insert("MPEG Card"),kata.insert("Short for Motion Picture Expert Group. The card that completes the CD-ROM to be able to display the full motion video smoothly, one full motion video must be run at a speed of 30 frames per second (fps). By installing MPEG card and CD-ROM drive on the PC, we can watch CD or karaoke movies on PC.")});
         dataModel.addRow(new Object[]{ 188, kata.insert("MMX/ Microprocessor Multimedia Exstensions"),kata.insert(": A new generation Pentium processor that can boost multimedia and communication performance up to 60% above the Pentium. In general MMX makes games/games more realistic, better videos and the facility of charts more perfect.")});
         dataModel.addRow(new Object[]{ 189, kata.insert("Offline"),kata.insert("A Status where a device cannot communicate with or is controlled by a computer.")});
         dataModel.addRow(new Object[]{ 190, kata.insert("Online"),kata.insert("Active and ready for operation, can communicate with or controlled by the computer.")});
         dataModel.addRow(new Object[]{ 191, kata.insert("Postcript Page Description Language"),kata.insert(": A programming language dedicated to defining the look of a document, usually providing flexible font capability and high-quality graphics.")});
         dataModel.addRow(new Object[]{ 192, kata.insert("Plotter"),kata.insert("Tools for drawing graphs, diagrams and other line graphs using a pen or electrostatic charge and toner.")});
         dataModel.addRow(new Object[]{ 193, kata.insert("Pentium"),kata.insert("The designation for Intel 80586 processors is also called P5. The Pentium processor is based on 64-bit operations and has 3.1 million transistors.")});
         dataModel.addRow(new Object[]{ 194, kata.insert("Pentium Pro"),kata.insert("The designation for Intel 80686 processors is also called P6. It is a 64-bit operation-based processor and has 5.5 million transistors. The target market is generally for networked computers with the Windows NT (New Technology) operating system.")});
         dataModel.addRow(new Object[]{ 195, kata.insert("Peripheral"),kata.insert("The term in the computer is used for equipment such as a brushed drive, printer, modem and other devices that are connected to the computer and controlled by the processor.")});
         dataModel.addRow(new Object[]{ 196, kata.insert("Prosesor"),kata.insert("It is also known as a single Chip center processing unit, which means translating and carrying out instruction-instructions through it, or a tool that functions as a computer brain.")});
         dataModel.addRow(new Object[]{ 197, kata.insert("Pixel/ Picture element"),kata.insert("The smallest elements are displayed or printed that can be handled by hardware and software to form letters, numbers or graphs. Or a grid point consisting of thousands of points one by one to form an image on the screen by a computer or on printer paper.")});
         dataModel.addRow(new Object[]{ 198, kata.insert("Port"),kata.insert("Sockets, a type of outlet on computer hardware, are also called input/output connectors; is the place to pass data in and out of the computing tool via cable.")});
         dataModel.addRow(new Object[]{ 199, kata.insert("Power Supply"),kata.insert("Tools that convert electricity from electrical sockets to lower voltages (especially 5 to 12 volts DC) are required by computer systems.")});
         dataModel.addRow(new Object[]{ 200, kata.insert("Query"),kata.insert("The process of retrieving data from a data base and providing it for use or a specific set of instructions to retrieve certain data on a recurring basis.")});
         dataModel.addRow(new Object[]{ 201, kata.insert("Real time"),kata.insert("Real time operation is an environment in which the activity of the machine matches the human perception of the time or where the operation of the computer runs at a speed with physical or external processes.")});
         dataModel.addRow(new Object[]{ 202, kata.insert("Resolution/ Resolusi"),kata.insert("The clarity or smoothness of details obtained by the monitor or printer in generating images. Resolution is usually used to show the total number of pixels displayed horizontally or vertically in the video view.")});
         dataModel.addRow(new Object[]{ 203, kata.insert("Router"),kata.insert("An intermediate tool on the communication network that launches message delivery.")});
         dataModel.addRow(new Object[]{ 204, kata.insert("Scan"),kata.insert("Moving the light-sensitive tools along the surface occupied images such as text pages, converting various fields on the surface into binary digits that can be interpretation by the computer.")});
         dataModel.addRow(new Object[]{ 205, kata.insert("Spreadsheet program"),kata.insert("Computer program packages used to process financial data and other data related to numbers such as budgets, cash flow analysis, and so on.")});
         dataModel.addRow(new Object[]{ 206, kata.insert("Shareware"),kata.insert("Programs that can be used on a limited basis for a particular trial period.")});
         dataModel.addRow(new Object[]{ 207, kata.insert("SRAM/ Static RAM"),kata.insert("The RAM chip can store about a quarter of data on the DRAM chip but is much faster than the DRAM. The price is still expensive.")});
         dataModel.addRow(new Object[]{ 208, kata.insert("Stack"),kata.insert("A reserved memory area where the program stores status data, such as procedures and functions that call return addresses, pass parameters, and (occasionally) a local variable.")});
         dataModel.addRow(new Object[]{ 209, kata.insert("Storage"),kata.insert("A tool that can physically be used to store data or information about files/archives and computer readable.")});
         dataModel.addRow(new Object[]{ 210, kata.insert("SIMM"),kata.insert("Abbreviation of Single In-line Memory Module. A small network board designed to occupy memory chip/IC.")});
         dataModel.addRow(new Object[]{ 211, kata.insert("SCSI/Small Computer System Interface"),kata.insert("High speed Paralet Interface that is used to connect the computer to other alata such as hard disk, printer, or to other computer network.")});
         dataModel.addRow(new Object[]{ 212, kata.insert("Serial port"),kata.insert("Connectors/sockets for input/output locations for serial data transmissions such as printers or mice.")});
         dataModel.addRow(new Object[]{ 213, kata.insert("Sound clip"),kata.insert("The Sound collection on a disk can be retrieved and incorporated into the document with the help of certain software or hardware.")});
         dataModel.addRow(new Object[]{ 214, kata.insert("Token Ring"),kata.insert("A unique data object structure or message that travels between the nodes of a network that is masked by a bracelet (closed topology, ring) and describes the status of the network.")});
         dataModel.addRow(new Object[]{ 215, kata.insert("Universal Serial Bus/ USB"),kata.insert("The combination of hardware, software and power cord that generates a way of communicating between all the different parts of the computer universally, one by one.")});
         dataModel.addRow(new Object[]{ 216, kata.insert("Validasi"),kata.insert("Testing to measure compliance with standards.")});
         dataModel.addRow(new Object[]{ 217, kata.insert("Visual Image"),kata.insert("Descriptions of images are stored and recorded in various ways and are an edited copy or reproduction for an image on a computer.")});
         dataModel.addRow(new Object[]{ 218, kata.insert("Video Card"),kata.insert("Card that converts analog data from the camera, VCR, laser disc, or television into digital data, so it can be stored on the hard drive. The video data is subsequently processed by the computer and the results can be displayed on the computer screen, the TV plane, or recorded to a video cassett")});
         dataModel.addRow(new Object[]{ 219, kata.insert("VGA/ Video Graphic Array"),kata.insert("It is a video adapter introduced by IBM in 1987, which duplicates samples of a physical variable, such as sound. The higher the rate, or the more samples are taken, the more tightly the digitising results resemble the original.")});
         dataModel.addRow(new Object[]{ 220, kata.insert("Wavetable synthesizer"),kata.insert("A stand-alone system, generating digital sound that is not due to manipulation of physical tools or sound recordings and can produce realistic sound without interruption.")});
         dataModel.addRow(new Object[]{ 221, kata.insert("WORM/ Write Once, Read Many"),kata.insert("Types of optical disks that are able and read repeat but cannot be changed once recorded with high capacity storage space.")});
         dataModel.addRow(new Object[]{ 222, kata.insert("Worksheet"),kata.insert("The term used to describe the data files formed and used by and with the electronic spreadsheet program. MS Excel Example")});
         dataModel.addRow(new Object[]{ 223, kata.insert("Xing MPEG Software"),kata.insert("Programs that can play MPEG applications in the form of films in CD/Video CD media.")});
         dataModel.addRow(new Object[]{ 224, kata.insert("ZIP"),kata.insert("Extension/Connection There is a file name indicating that the file has been compressed by the PKZIP program. Example motor. zip")});
// TODO add your handling code here:
    }//GEN-LAST:event_TampilkataActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(EXIT_ON_CLOSE); // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new ListKata1English().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new HomePage().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new MenuEnglish().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new AboutEnglish().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListKata2English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListKata2English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListKata2English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListKata2English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListKata2English().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JButton Tampilkata;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
