/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Redesign_UI;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */

public class ListKata2 extends javax.swing.JFrame {
        
        
    /**
     * Creates new form ListKata
     */
    public ListKata2() {
       
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public String insert(String data){ //method untuk memasukkan kunci dan nilai
        /*int hashVal=hashFunc(data); //key yang dimasukkan akan diproses di hashFunc di dalam variabel hashval
        ListNode list=hashArray[hashVal]; //nilai dari hashVasl akan disimpan di hashArray dalam bentuk list 
        
       /* while(list !=null){ //jika list tidak bernilai null maka akan di looping
            if (list.key.equals(key)) { //jika list dari key objek sama dengan key yang dimasukkan 
                break; //maka di break
            }
            list=list.next; //kemuadian list akan di next
        }
        if (list != null) { //jika list tidak bernilai null
            list.value=value; //maka value objek dari list bernilai value yang di inputkan 
        }*/
       // else{   //jika tidak
            /*if (count >=0.75*hashArray.length) {    //jika count lebih dari 0,75*ukuran array
                resize();   //maka akan di resize
            }*/
            /*ListNode newNode=new ListNode(); //inisialisasi newnode dengan objek listnode baru
            newNode.key=data; //nilai key objek dari newnode bernilai key inputan 
            //newNode.value=value;    //dan nilai value obek dari newnode bernilai value inputan
            newNode.next=hashArray[hashVal];    
            hashArray[hashVal]=newNode;
            count++;*/
        //}
            return data;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        Tampilkata = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 60, 60));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 40));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 60));

        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 50));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, 40));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 40, 40));

        Tampilkata.setBackground(new java.awt.Color(153, 153, 255));
        Tampilkata.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Tampilkata.setForeground(new java.awt.Color(102, 102, 102));
        Tampilkata.setText("Tampilkan Daftar kata ");
        Tampilkata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkataActionPerformed(evt);
            }
        });
        getContentPane().add(Tampilkata, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 330, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Daftar 2 dari 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 760, -1, -1));

        tabel.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kata", "Makna"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 560, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menudaftarkata.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TampilkataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkataActionPerformed
          DefaultTableModel dataModel = (DefaultTableModel) tabel.getModel();
          ListKata2 kata= new ListKata2();
          
          tabel.setAutoCreateColumnsFromModel(true);
          dataModel.addRow(new Object[]{ 101,kata.insert("DECnet/OSI"),kata.insert("Protokol DECnet yang kompatibel dengan phase V produk Digital Network Architecture (DNA). Protocol ini mendukung sistem terbuka OSI.")});
          dataModel.addRow(new Object[]{ 102,kata.insert("Decreament"),kata.insert("Untuk mengurangi nilai suatu variabel satu demi satu.")});
          dataModel.addRow(new Object[]{ 103,kata.insert("Decompress"),kata.insert("Mengembalikan file-file yang telah dimampatkan (compress) ke keadaan semula.")});
          dataModel.addRow(new Object[]{ 104,kata.insert("Default"),kata.insert("Hasil penyetelan tetap untuk menjalankan sebuah program atau aplikasi")});
          dataModel.addRow(new Object[]{ 105,kata.insert("Demodulation"),kata.insert("Proses mengubah sinyal analog menjadi bentuk digital.")});
          dataModel.addRow(new Object[]{ 106,kata.insert("Desktop"),kata.insert("Salah satu model kemasan komputer yang sengaja dirancang untuk ditempatkan di atas meja kerja.")});
          dataModel.addRow(new Object[]{ 107,kata.insert("Desktop Publishing"),kata.insert("Software yang digunakan untuk membuat dan mengatur format pada pencetakkan majalah dan buku secara mudah. Contoh software DTP adalah Ventura dan Pagemaker.")});
          dataModel.addRow(new Object[]{ 108,kata.insert("Dial"),kata.insert("Proses terhubungnya komputer ke suatu stasiun atau sebuah alamat Internet melalui saluran komunikasi.")});
          dataModel.addRow(new Object[]{ 109,kata.insert("Dial Line"),kata.insert("Istilah lain untuk menyebutkan penghubung saluran (switch connection).")});
          dataModel.addRow(new Object[]{ 110,kata.insert("Dial Up"),kata.insert("jenis komunikasi yang menggunakan modem dan saluran telepon biasa untuk bisa berhubungan antara komputer yang satu dengan komputer yang lain, atau bisa juga berarti provider Internet yang memanfaatkan saluran telepon sebagai saluran utamanya. Hubungan ini hanya bersifat sementara.")});
          dataModel.addRow(new Object[]{ 111,kata.insert("Dial Up Line"),kata.insert("Jalur komunikasi yang digunakan pada proses dial up, terutama jaringan umum atau jaringan telepon biasa.")});
          dataModel.addRow(new Object[]{ 112,kata.insert("DIR"),kata.insert("Dalam sistem operasi DOS berarti perintah untuk menampilkan daftar semua file dalam disk aktif ke layar.")});
          dataModel.addRow(new Object[]{ 113,kata.insert("Dial Up Terminal"),kata.insert("Sebuah terminal pada saluran pemindah.")});
          dataModel.addRow(new Object[]{ 114,kata.insert("Disconnect"),kata.insert("Istilah untuk menyatakan pemutusan hubungan dengan saluran komunikasi atau keadaan tidak terhubung dengan jaringan manapun.")});
          dataModel.addRow(new Object[]{ 115,kata.insert("Disconnect time-out"),kata.insert("Batas waktu yang digunakan oleh switched network untuk melakukan pemutusan hubungan komunikasi apabila sebuah stasiun dalam keadaan tidak aktif melebihi batas waktu tersebut.")});
          dataModel.addRow(new Object[]{ 116,kata.insert("Discreate Circuitry"),kata.insert("Membangun sirkuit elektronik dengan memasang beberapa bagian secara individual. Kebalikan dari IC, dan saat ini discreate circuitry jarang dipakai karena mahal dan kurang handal.")});
          dataModel.addRow(new Object[]{ 117,kata.insert("Disk"),kata.insert("Piringan tipis yang dilapisi bahan magnetik (oksida besi) yang mampu menyimpan sejumlah data atau informasi. Pembacaan dan penulisan informasi dipusatkan pada track.")});
          dataModel.addRow(new Object[]{ 118,kata.insert("Disk Cleaner"),kata.insert("Disket yang membersihkan head suatu disk drive")});
          dataModel.addRow(new Object[]{ 119,kata.insert("Diskcopy"),kata.insert("Program under DOS yang berfungsi untuk menyalin keseluruhan isi suatu disk dengan jenis drive yang sama.")});
          dataModel.addRow(new Object[]{ 120,kata.insert("Disk Drive"),kata.insert("Alat tambahan yang digunakan untuk meletakkan piringan magnetik, memutar piringan dan menggerakkan head baca/tulis pada posisi yang diinginkan ketika mengakses informasi dari dalam disk")});
          dataModel.addRow(new Object[]{ 121,kata.insert("Diskette"),kata.insert("Piringan magnetik tipis, lentur dan dibungkus dalam kemasan berbentuk kotak dari bahan plastik, digunakan untuk menyimpan sejumlah data/informasi. Disket umumnya berukuran 3½ inchi.")});
          dataModel.addRow(new Object[]{ 122,kata.insert("Display"),kata.insert("Hardware yang menyajikan hasil keluaran komputer dalam bentuk visual.")});
          dataModel.addRow(new Object[]{ 123,kata.insert("Documentation"),kata.insert(" Dokumentasi yang menyimpan deskripsi tertulis sebuah program termasuk nama program, fungsi program, masukan/keluaran yang dibutuhkan, kemungkinan ditulis dalam algoritma, bagaimana struktur datanya, dan sebagainya.")});
          dataModel.addRow(new Object[]{ 124,kata.insert("Domain"),kata.insert("Definisi dari alamat di Internet, yang juga merujuk ke sebuah negara di mana situs web tersebut digunakan. Misalnya co.id untuk Indonesia. Sedangkan co atau com untuk lembaga komersial dan net untuk lembaga yang berhubungan dengan Internet.")});
          dataModel.addRow(new Object[]{ 125,kata.insert("Domain Name"),kata.insert("Bagian dari URL atau alamat situs yang menunjukkan kepemilikan, misalnya andinomaseleno.com menunjukkan alamat itu dimiliki oleh andinomaseleno.")});
          dataModel.addRow(new Object[]{ 126,kata.insert("Drag"),kata.insert("Istilah yang menggambarkan kegiatan menggerakkan mouse sambil tetap menekam tombol mouse")});
          dataModel.addRow(new Object[]{ 127,kata.insert("Drag and Drop"),kata.insert("Istilah yang menggambarkan kegiatan memilih suatu obyek dan menggerakkan mouse ke lokasi baru sambil tetap menekan tombol mouse sebelah kiri (drag), kemudian meletakkan obyek di lokasi tersebut (drop).")});
          dataModel.addRow(new Object[]{ 128,kata.insert("Duplex"),kata.insert("1. Jalur Komunikasi yang mampu melakukan pengiriman data dua arah. 2. Sistem komputer yang menggunakan 2  CPU yang saling terhubung. ")});
          dataModel.addRow(new Object[]{ 129,kata.insert("Duplexed System"),kata.insert("Lingkungan komunikasi data yaitu sistem yang memiliki dua alat yang berbeda dan tidak saling mempengaruhi. Setiap alat mampu melaksanakan fungsinya; ada kemungkinan salah satu alat akan dianggap sebagai cadangan.")});
          dataModel.addRow(new Object[]{ 130,kata.insert("EFT"),kata.insert("(Electronic Funds Transfer) : Teknik pengiriman atau pertukaran data-data transaksi keuangan secara elektronik.")});
          dataModel.addRow(new Object[]{ 131,kata.insert("Eject"),kata.insert("Perintah yang diberikan pada printer untuk menempatkan kertas di awal halaman. Apabila saat ini posisi kertas berada di tengah, maka sisa halaman akan diabaikan dan meletakkan kertas berikutnya di awal halaman.")});
          dataModel.addRow(new Object[]{ 132,kata.insert("E-mail"),kata.insert("Surat-menyurat melalui internet.Pengguna dapat saling bertukar berita. Berita-berita itu akan dikumpulkan dalam sebuah file untuk pengalamatan yang berupa mailbox, sehingga pengguna dapat membaca berita yang ditujukan kepadanya kapan saja.")});
          dataModel.addRow(new Object[]{ 133,kata.insert("E-mail Address"),kata.insert("Alamat yang dipakai pada proses pengiriman e-mail ke tujuannya. Alamat tersebut dibuat berdasarkan DNS.")});
          dataModel.addRow(new Object[]{ 134,kata.insert("E-mail Virus"),kata.insert("Virus yang dikirimkan sebagai file lampiran pada e-mail, virus baru akan bekerja dan menginfeksi jika kita membuka file attachment tersebut. Sebagian besar adalah virus Macro yang menyerang aplikasi Microsoft Word, biasanya file virus tersebut berekstensi .exe. Contohnya seperti virus Worm.ExploreZip.")});
          dataModel.addRow(new Object[]{ 135,kata.insert("Encode"),kata.insert("Kegiatan mempersiapkan suatu rutin program ke dalam bahasa mesin sehingga dapat segera dilaksanakan oleh komputer.")});
          dataModel.addRow(new Object[]{ 136,kata.insert("Encoder"),kata.insert("Suatu sistem komputer atau sistem jaringan yang hanya mampu menerima satu masukan saja, yang setiap masukan akan menghasilkan beberapa kombinasi hasil keluaran. ")});
          dataModel.addRow(new Object[]{ 137,kata.insert("Encryption"),kata.insert("Penerjemahan data menjadi kode rahasia. Enkripsi adalah cara yang paling efektip untuk memperoleh pengamanan data. Untuk membaca file yang di-enkrip, kita harus mempunyai akses terhadap kata sandi yang memungkinkan kita men-dekrip pesan tersebut. Data yang tidak di-enkrip disebut plain text, sedangkan yang di-enkrip disebut cipher text")});
          dataModel.addRow(new Object[]{ 138,kata.insert("End"),kata.insert("Tombol pada keyboard, berfungsi untuk menggerakkan kursor ke akhir baris.")});
          dataModel.addRow(new Object[]{ 139,kata.insert("Error"),kata.insert("Istilah untuk menunjukkan bahwa terdapat suatu penyimpangan dalam software atau kerusakan hardware")});
          dataModel.addRow(new Object[]{ 140,kata.insert("Ethernet"),kata.insert("Sebuah standar LAN meliputi kabel dan skema protokol komunikasi yang dikembangkan oleh Xerox Corporation. Sekarang Ethernet menjadi protokol yang banyak digunakan dan diadaptasi oleh perusahaan lain. ")});
          dataModel.addRow(new Object[]{ 141,kata.insert("Ethernet Cabel"),kata.insert("Semua kabel media untuk jaringan Ethernet. Contoh Ethernet cable yaitu kabel jenis 10base5, UTP/STP. ")});
          dataModel.addRow(new Object[]{ 142,kata.insert("Ethernet Meltdown"),kata.insert("Peristiwa yang menimbulkan kejenuhan di Ethernet, disebabkan oleh masuknya paket-paket data tak resmi. Peristiwa ini hanya berlangsung dalam waktu singkat.")});
          dataModel.addRow(new Object[]{ 143,kata.insert("Ether Talk"),kata.insert("Paket-paket AppleTalk terenkapsulasi yang dilewatkan pada kabel Ethernet.")});
          dataModel.addRow(new Object[]{ 144,kata.insert("Eudora"),kata.insert("Program aplikasi layanan e-mail di Internet.Facsimile : Alat pengirim dokumen atau gambar dari satu tempat ke tempat lain dengan menggunakan saluran telepon. Pengiriman bisa dilakukan apabila pengirim dan penerima sama-sama mengaktifkan mesin ini. ")});
          dataModel.addRow(new Object[]{ 145,kata.insert("Fading"),kata.insert("Gangguan saluran transmisi, terutama pada sistem gelombang mikro ketika sinyal-sinyal yang dikirim melalui berbagai jalur ke penerima mengalami perubahan karena kondisi atmosfir.")});
          dataModel.addRow(new Object[]{ 146,kata.insert("Failure"),kata.insert("Pernyataan yang menunjukkan bahwa alat terkait tidak berjalan dengan semestinya.")});
          dataModel.addRow(new Object[]{ 147,kata.insert("Female Connector"),kata.insert("Sebuah plug atau socket yang memiliki receptacles. Lawannya adalah \"konektor pria\" yang memiliki pin")});
          dataModel.addRow(new Object[]{ 148,kata.insert("Fetch"),kata.insert("Program software untuk memindahkan file yang dikembangkan oleh Dartmouth College untuk Macintosh. Program ini menyediakan akses ke FTP yang bersifat user friendly.")});
          dataModel.addRow(new Object[]{ 149,kata.insert("File"),kata.insert("File terdiri dari sekumpulan record-record yang saling berhubungan. Setiap record memiliki nomor yang disesuaikan dengan posisinya dalam file.")});
          dataModel.addRow(new Object[]{ 150,kata.insert("Folder"),kata.insert("Pada lingkungan Graphical User Interface (GUI) seperti Windows dan Macintosh, folder adalah suatu objek yang dapat berisi beberapa dokumen. Folder digunakan untuk menata informasi. Pada DOS dan UNIX, folder disebut direktori (directory).")});
          dataModel.addRow(new Object[]{ 151,kata.insert("Gigabyte"),kata.insert("Suatu istilah untuk menyebutkan suatu citra yang memiliki warna abu-abu, alias hitam dan putih. Greyscale menunjukkan jumlah warna (dari abu-abu, hingga hitam – putih) yang ada dalam satu citra. Makin besar angka Grayscale, citra yang terbentuk makin mendekati kenyataan.")});
          dataModel.addRow(new Object[]{ 152,kata.insert("Gigacycle"),kata.insert("Satuan ukuran frekuensi dengan 1 Gigacycle = 1 milyar Hertz.")});
          dataModel.addRow(new Object[]{ 153,kata.insert("Google"),kata.insert("Nama search engine di Internet.")});
          dataModel.addRow(new Object[]{ 154,kata.insert("Glossary"),kata.insert("Daftar istilah berikut penjelasan pengertian istilah-istilah tersebut.")});
          dataModel.addRow(new Object[]{ 155,kata.insert("Gopher"),kata.insert("Suatu sistem informasi berbasis menu dalam Internet yang populer karena kemampuannya berhubungan dalam situs gopher yang lain dalam menu yang sama.")});
          dataModel.addRow(new Object[]{ 156,kata.insert("GPRS"),kata.insert("(General Packet Radio Service ) : Layanan komunikasi berbasis paket, tanpa kabel sebagai media komunikasi. Layanan ini diperuntukkan bagi komputer jinjing (notebook). Dasar dari GPRS adalah komunikasi GSM (Global System for Mobile Communication). Kecepatan yang ditawarkan mulai dari 56 Kbps sampai dengan 114 Kbps, memungkinkan untuk mengakses Internet dengan lebih cepat. ")});
          dataModel.addRow(new Object[]{ 157,kata.insert("GSM"),kata.insert("(Global System for Mobile Communication) : Seluler digital atau standar PCS yang digunakan di seluruh dunia. GSM merupakan standar yang paling banyak digunakan di Eropa dan Asia Tenggara. ")});
          dataModel.addRow(new Object[]{ 158,kata.insert("Guestbook"),kata.insert("Fasilitas interaktif dalam sebuah halaman web yang mengizinkan pengunjungnya untuk menulis pesan.")});
          dataModel.addRow(new Object[]{ 159,kata.insert("Homepage"),kata.insert("Halaman pertama dari suatu Web Site.")});
          dataModel.addRow(new Object[]{ 160,kata.insert("Host"),kata.insert("Istilah yang digunakan untuk menunjuk sebuah komputer yang memungkinkan penggunanya terhubung ke Internet.")});
          dataModel.addRow(new Object[]{ 161,kata.insert("Host Name"),kata.insert("Nama dari komputer dalam Internet, digunakan untuk menunjukkan skema penamaan URL.")});
          dataModel.addRow(new Object[]{ 162,kata.insert("HTTP"),kata.insert("(Hyper Text Transfer Protocol) : Sebuah metode atau protokol untuk mendowload file ke komputer. Protokol ini berbasis hyper text, sebuah format teks yang umum digunakan di Internet. ")});
          dataModel.addRow(new Object[]{ 163,kata.insert("Icon"),kata.insert("Tipe GIF Spesial yang memungkinkan tampilan gambar tersebut dimunculkan sedikit demi sedikit ketika sebuah halaman web sedang didownload. ")});
          dataModel.addRow(new Object[]{ 164,kata.insert("Internet"),kata.insert("Istilah umum yang dipakai untuk menunjuk Network tingkat dunia yang terdiri dari komputer dan layanan servis atau sekitar 30 sampai 50 juta pemakai komputer dan puluhan sistem informasi termasuk e-mail, Gopher, FTP dan World Wide Web.")});
          dataModel.addRow(new Object[]{ 165,kata.insert("Internet Device"),kata.insert("Alat canggih seperti komputer yang dipergunakan untuk dapat berkomunikasi atau berinteraksi melalui Internet, baik untuk surfing, mengirim dan menerima e-mail, bahkan untuk ber-chatting, baik menggunakan teks, suara, gambar maupun video, misal : notebook, palmtop, handphone, Internet-TV.")});
          dataModel.addRow(new Object[]{ 166,kata.insert("Internet Explorer"),kata.insert("Suatu browser Web gratis terkenal yang diproduksi oleh Microsoft.")});
          dataModel.addRow(new Object[]{ 167,kata.insert("Intranet"),kata.insert("Sumber daya informasi yang digunakan untuk kepentingan internal dari suatu instansi atau perusahaan dengan menggunakan jaringan komputer yang ada.")});
          dataModel.addRow(new Object[]{ 168,kata.insert("Java"),kata.insert("Bahasa pemrograman untuk menciptakan isi yang aktif dalam halaman Web, juga dapat dijalankan dalam semua komputer. Applet Java diambil/diakses dari halaman Web dan dijalankan secara total. ")});
          dataModel.addRow(new Object[]{ 169,kata.insert("JavaScript"),kata.insert("Bahasa script interpreter untuk menciptakan isi yang aktif dalam halaman Web.")});
          dataModel.addRow(new Object[]{ 170,kata.insert("JPEG"),kata.insert("(Joint Photographic Expert Group) :Format file yang memuat data berupa gambar. Gambar JPEG terkompresi secara lossy, sehingga kualitas gambar diturunkan untuk mendapatkan ukuran file yang kecil. Walaupun demikian perbedaan kualitas tersebut tidak akan dapat terlihat untuk gambar-gambar tertentu. JPEG biasanya digunakan untuk gambar-gambar yang tidak jelas batas warnanya, seperti foto, lukisan, dll. ")});
          dataModel.addRow(new Object[]{ 171,kata.insert("Kbps"),kata.insert("Kilobytes per second.")});
          dataModel.addRow(new Object[]{ 172,kata.insert("KHz"),kata.insert("Satuan unit frekuensi yang sama dengan 1000 siklus per detik. ")});
          dataModel.addRow(new Object[]{ 173,kata.insert("Konektor Power"),kata.insert("Pin yang menyambungkan motherboard dengan power supply di casing sebuah komputer. Pada motherboard tipe AT, casing yang dibutuhkan adalah tipe AT juga. Konektor power tipe AT terdiri dari dua bagian, dimana dua kabel dari power supply akan menancap. Pada tipe ATX, kabel power supply menyatu dalam satu header yang utuh sehingga tinggal menancapkannya di motherboard. Kabel ini terdiri dari dua kolom sesuai dengan pin di motherboard yang terdiri atas dua larik pin juga. Ada beberapa motherboard yang menyediakan dua tipe konektor power, AT dan ATX. Kebanyakan motherboard terbaru sudah bertipe ATX.")}); 
          dataModel.addRow(new Object[]{ 174,kata.insert("LAN"),kata.insert("Sebuah jaringan yang dibangun pada sebuah lokasi seperti di rumah ataupun gedung perkantoran. Bisa diartikan juga sebagai sebuah sistem komunikasi komputer yang jaraknya dibatasi tidak lebih dari beberapa kilometer dan menggunakan koneksi high-speed antara 2 hingga 100 Mbps. ")});
          dataModel.addRow(new Object[]{ 175,kata.insert("Layer"),kata.insert("Lapisan (konsep) dalam networking. Berbagai model komunikasi seperti OSI dan TCP/IP terdiri atas beberapa layer yang menyusun protokol tersebut.")});
          dataModel.addRow(new Object[]{ 176,kata.insert("LCD"),kata.insert("(Liquid Crystal Display) : Jenis tampilan layar yang menggunakan persenyawaan cair yang mempunyai struktur molekul polar, diapit antara dua elektroda yang transparan. Bila medan listrik diberikan, molekul menyesuaikan posisinya pada medan, membentuk susunan kristalin yang mempolarisasi cahaya yang melaluinya. ")});
          dataModel.addRow(new Object[]{ 177,kata.insert("LED"),kata.insert("(Light Emitting Diode) : Sebuah lampu kecil yang digunakan sebagai penanda atau pointer. ")});
          dataModel.addRow(new Object[]{ 178,kata.insert("Link"),kata.insert("Sambungan atau koneksi dari sebuah sumber ke sumber yang lain. Misalnya dalam sistem networking atau Internet.")});
          dataModel.addRow(new Object[]{ 179,kata.insert("Listserv"),kata.insert("Software manajemen mailing list.")});
          dataModel.addRow(new Object[]{ 180,kata.insert("Load Time"),kata.insert("Waktu yang dibutuhkan untuk mengambil/membuka halaman Web pada komputer.")});
          dataModel.addRow(new Object[]{ 181,kata.insert("Locate"),kata.insert("Perintah yang digunakan dalam Linux/Unix untuk mendapatkan file tertentu. Hanya saja perintah locate ini harus didahului dengan slocate untuk melakukan updating informasi file dalam host tersebut.")});
          dataModel.addRow(new Object[]{ 182,kata.insert("Localhost"),kata.insert("Di dunia Networking, Localhost merupakan istilah yang digunakan untuk host itu sendiri. Nama localhost digunakan untuk konfigurasi aplikasi sebelum benar - benar mendapatkan hostname dari hostmasternya.")});
          dataModel.addRow(new Object[]{ 183,kata.insert("Log"),kata.insert("Catatan yang merekam segala aktifitas suatu aplikasi dijalankan. terkadang Log juga digunakan untuk menganalisa status suatu aplikasi.")});
          dataModel.addRow(new Object[]{ 184,kata.insert("Login"),kata.insert("Keluar atau menutup, sama artinya dengan sign out. Multiuser systemSebarang sistem komputer yang dapat dipakai oleh lebih dari satu orang.")});
          dataModel.addRow(new Object[]{ 185,kata.insert("Modem"),kata.insert("Singkatan dari modulator/demodulator; alat komunikasi yang memungkinkan komputer mengirimkan informasi melalui saluran telepon piawaian")});
          dataModel.addRow(new Object[]{ 186,kata.insert("Motherboard"),kata.insert("Komponen terbesar di dalam PC. Disebut ‘mother’ karena papan ini menjadi tempat seluruh komponen PC seperti prosesor, memori utama, rangkaian pendukung dan bus controller.")});
          dataModel.addRow(new Object[]{ 187,kata.insert("MPEG Card"),kata.insert("Kependekan dari Motion Picture Expert Group. Yaitu card yang melengkapi CD-ROM agar mampu menampilkan full motion video secara mulus, satu full motion video harus dijalankan pada kecepatan 30 frame per detik (fps). Dengan memasang MPEG card dan CD-ROM drive di PC, kita boleh menonton film CD maupun berkaraoke di PC. ")});
          dataModel.addRow(new Object[]{ 188,kata.insert("MMX/ Microprocessor Multimedia Exstensions"),kata.insert("Prosesor Pentium generasi baru yang dapat mendongkrak kinerja multimedia dan komunikasi sampai 60% di atas pentium. Secara umum MMX membuat game/ permainan lebih realistik, video lebih baik dan fasiliti grafik lebih sempurana.")});
          dataModel.addRow(new Object[]{ 189,kata.insert("Offline"),kata.insert("Status dimana suatu alat tidak dapat berkomunikasi dengan atau dikontrol oleh komputer.")});
          dataModel.addRow(new Object[]{ 190,kata.insert("Online"),kata.insert("Aktif dan siap untuk operasi, dapat berkomunikasi dengan atau dikontrol oleh komputer.")});
          dataModel.addRow(new Object[]{ 191,kata.insert("Postcript Page Description Language"),kata.insert("Bahasa pemrograman yang khusus untuk mendefinisikan tampilan dokumen, biasanya menyediakan kapabilitas huruf yang fleksibel dan grafik dengan kualitas tinggi.")});
          dataModel.addRow(new Object[]{ 192,kata.insert("Plotter"),kata.insert("Alat untuk menggambar grafik, diagram dan grafik garis lainnya yang menggunakan pena atau muatan elektrostatik dan toner.")});
          dataModel.addRow(new Object[]{ 193,kata.insert("Pentium"),kata.insert("Sebutan untuk prosesor Intel 80586 disebut juga P5. Prosesor Pentium berasaskan operasi 64-bit dan memiliki 3.1 juta buah transistor.")});
          dataModel.addRow(new Object[]{ 194,kata.insert("Pentium Pro"),kata.insert("Sebutan untuk prosesor Intel 80686 disebut juga P6. Yaitu prosesor berasaskan operasi 64-bit dan memiliki 5.5 juta buah transistor. Sasaran pasar umumnya untuk komputer jaringan dengan sistem operasi Windows NT (New Technology).")});
          dataModel.addRow(new Object[]{ 195,kata.insert("Peripheral"),kata.insert("Istilah dalam komputer yang digunakan untuk peralatan seperti penggerak disik, printer, modem dan lainnya yang dihubungkan ke komputer dan dikendalikan oleh prosesornya.")});
          dataModel.addRow(new Object[]{ 196,kata.insert("Prosesor"),kata.insert("Disebut juga unit pemrosesan pusat chip tunggal, yaitu alat yang menterjemahkan dan melaksanakan instruksi-instruki yang melaluinya, atau alat yang berfungsi sebagai otak komputer.")});
          dataModel.addRow(new Object[]{ 197,kata.insert("Pixel/ Picture element"),kata.insert("Unsur terkecil yang ditampilkan atau dicetak yang dapat ditangani oleh hardware dan software untuk membentuk huruf, angka atau grafik. Atau suatu titik kisi-kisi yang terdiri dari ribuan titik satu per satu untuk membentuk suatu gambar pada layar oleh komputer atau pada kertas printer.")});
          dataModel.addRow(new Object[]{ 198,kata.insert("Port"),kata.insert("Soket, sejenis stopkontak pada hardware komputer, disebut juga konektor input/ output; yaitu tempat untuk meneruskan data masuk dan keluar dari alat komputasi melalui kabel.")});
          dataModel.addRow(new Object[]{ 199,kata.insert("Power Supply"),kata.insert("Alat yang mengubah listrik dari soket listrik menjadi tegangan yang lebih rendah (khususnya 5 sampai 12 volt DC) yang dibutuhkan oleh sistem komputer.")});
          dataModel.addRow(new Object[]{ 200,kata.insert("Query"),kata.insert("Proses pengambilan data dari suatu asas data dan menyediakannya untuk dipakai atau suatu himpunan tertentu yang berisi instruksi untuk mengambil data tertentu secara berulang.")});
          dataModel.addRow(new Object[]{ 201,kata.insert("Real time"),kata.insert("Operasi real time adalah lingkungan di mana aktiviti mesin sesuai dengan persepsi manusia mengenai waktu atau di mana operasi komputer berjalan dengan kecepatan dengan proses fizikal atau eksternal.")});
          dataModel.addRow(new Object[]{ 202,kata.insert("Resolution/ Resolusi"),kata.insert("Kejernihan atau kehalusan detil yang diperoleh monitor atau printer dalam menghasilkan gambar. Resolusi biasanya dipakai untuk menunjukkan jumlah total pixel yang ditampilkan secara horisontal atau vertikal pada tampilan video.")});
          dataModel.addRow(new Object[]{ 203,kata.insert("Router"),kata.insert("Alat perantara pada jaringan komunikasi yang melancarkan pengiriman pesan. ")});
          dataModel.addRow(new Object[]{ 204,kata.insert("Scan"),kata.insert("Menggerakkan alat peka cahaya sepanjang permukaan yang ditempati gambar seperti halaman teks, mengkonversi berbagai bidang pada permukaan menjadi digit biner yang dapat diinterpretasi oleh komputer.")});
          dataModel.addRow(new Object[]{ 205,kata.insert("Spreadsheet program"),kata.insert("Paket program komputer yang digunakan untuk memproses data keuangan dan data lain yang berhubungan dengan angka seperti anggaran, analisa cash flow, dan sebagainya.")});
          dataModel.addRow(new Object[]{ 206,kata.insert("Shareware"),kata.insert("Program yang boleh digunakan secara terhad untuk jangka waktu percobaan tertentu.")});
          dataModel.addRow(new Object[]{ 207,kata.insert("SRAM/ Static RAM"),kata.insert("Chip RAM yang dapat menyimpan sekitar seperempat data pada chip DRAM tetapi jauh lebih cepat dari pada DRAM. Harganya masih mahal.")});
          dataModel.addRow(new Object[]{ 208,kata.insert("Stack"),kata.insert("Daerah memori yang dicadangkan dimana program menyimpan data status, seperti prosedur dan fungsi yang memanggil return address, meneruskan parameter, dan (kadang-kadang) variabel setempat.")});
          dataModel.addRow(new Object[]{ 209,kata.insert("Storage"),kata.insert("Suatu alat yang secara fisik dapat digunakan menyimpan data atau informasi mengenai fail/ arsip dan dapat dibaca komputer.")});
          dataModel.addRow(new Object[]{ 210,kata.insert("SIMM"),kata.insert("Singkatan dari Single In-line Memory Module. Papan rangkaian kecil yang dirancang untuk menempati chip/IC memori.")});
          dataModel.addRow(new Object[]{ 211,kata.insert("SCSI/Small Computer System Interface"),kata.insert("Interface paralet dengan tahap kecepatan tinggi yang digunakan untuk menghubungkan komputer ke alata lainnya seperti harddisk, printer, atau ke komputer lain secara jaringan.")});
          dataModel.addRow(new Object[]{ 212,kata.insert("Serial port"),kata.insert("Konektor/ soket untuk lokasi input/output untuk transmisi data serial seperti printer atau mouse.")});
          dataModel.addRow(new Object[]{ 213,kata.insert("Sound clip"),kata.insert("Koleksi suara pada sebuah disk yang dapat diambil dan digabungkan ke dalam dokumen dengan bantuan software atau hardware tertentu.")});
          dataModel.addRow(new Object[]{ 214,kata.insert("Token Ring"),kata.insert("Struktur objek data yang unik atau pesan yang berkeliling secara bersambung di antara node-node suatu jaringan yang bertopologi gelang (topologi tertutup, ring) dan menggambarkan status yang ada di jaringan.")});
          dataModel.addRow(new Object[]{ 215,kata.insert("Universal Serial Bus/ USB"),kata.insert("Kombinasi hardware, software dan kabel listrik yang menghasilkan suatu cara berkomunikasi antara semua bagian komputer yang berlainan secara universal, satu per satu.")});
          dataModel.addRow(new Object[]{ 216,kata.insert("Validasi"),kata.insert("Pengujian untuk mengukur persesuaian dengan piawaian .")});
          dataModel.addRow(new Object[]{ 217,kata.insert("Visual Image"),kata.insert("Deskripsi gambar yang disimpan dan dirakam dengan berbagai cara dan merupakan suatu salinan atau reproduksi yang diedit untuk sebuah citra di komputer.")});
          dataModel.addRow(new Object[]{ 218,kata.insert("Video Card"),kata.insert("Card yang dapt mengubah data analog dari kamera, VCR, laser disc, maupun televisi menjadi data digital, sehingga dapat disimpan di harddisk. Selanjutnya data video diolah oleh komputer dan hasilnya dapat ditampilkan di layar komputer, pesawat TV, atau dirakam ke kaset video.")});
          dataModel.addRow(new Object[]{ 219,kata.insert("VGA/ Video Graphic Array"),kata.insert("Merupakan video adapter yang diperkenalkan oleh IBM pada 1987, yang menduplikasikan sampel suatu variabel fisik, seperti suara. Makin tinggi samping rate atau makin banyak sampel diambil persatuan waktu, makin rapat hasil digitasi menyerupai aslinya.")});
          dataModel.addRow(new Object[]{ 220,kata.insert("Wavetable synthesizer"),kata.insert("Sistem yang berdiri sendiri, membangkitkan suara digital yang bukan karena manipulasi alat fisik atau rekaman suara dan dapat menghasilkan suara yang realistis tanpa gangguan.")});
          dataModel.addRow(new Object[]{ 221,kata.insert("WORM/ Write Once, Read Many"),kata.insert("Jenis disk optik yang dapat dan dibaca ulang tetapi tidak dapat diubah setelah dirakam dengan ruang penyimpanan kapasiti tinggi.")});
          dataModel.addRow(new Object[]{ 222,kata.insert("Worksheet"),kata.insert("Istilah yang digunakan untuk menggambarkan fail data yang dibentuk dan dipakai oleh dan dengan program lembar kerja elektronik. Contoh MS Excel")});
          dataModel.addRow(new Object[]{ 223,kata.insert("Xing MPEG Software"),kata.insert("Program yang dapat memainkan aplikasi MPEG berupa filem-filem dalam media ")});
          dataModel.addRow(new Object[]{ 224,kata.insert("ZIP"),kata.insert("Extensi/Sambungan ada nama fail yang mengindikasikan bahwa fail tersebut sudah dikompres oleh program PKZIP. Contoh motor.zip")}); 

// TODO add your handling code here:
    }//GEN-LAST:event_TampilkataActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(EXIT_ON_CLOSE); // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new ListKata().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new HomePage().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new MenuIndo().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new About().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListKata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListKata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListKata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListKata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListKata2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JButton Tampilkata;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
