
import javax.swing.JFrame;




public class Kamus_Versi_English extends javax.swing.JFrame  { 
    private Data1[] hashArray; //deklarasi array bernama hashArray bertipe objek ListNode
    private int size;
    /**
     * Creates new form Versi_Bahasa
     */
    public Kamus_Versi_English(int size) {   //Constructor
        this.size = size;
        hashArray=new Data1[size]; //isi Array maksimal 200
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void insert(String key,String value){ //method untuk memasukkan kunci dan nilai
        Data1 item = new Data1(key, value);
        String kunci = item.getKey();
        int hashval = hashFunc(kunci);
        while(hashArray[hashval] != null){
            ++hashval;
            hashval %= size;
        }
        hashArray[hashval] = item;
        
    }
    /*private void resize(){
        ListNode[] newtable=new ListNode[hashArray.length*2];
        for (int i = 0; i < hashArray.length; i++) {
            ListNode list=hashArray[i];
            while(list != null){
                ListNode next=list.next;
                
                int hash=(Math.abs(list.key.hashCode()))% newtable.length;
                list.next=newtable[hash];
                newtable[hash]=list;
                list=next;
            }
        }
        hashArray=newtable;
    }*/
    public int hashFunc(String key){
        return (Math.abs(key.hashCode())) % hashArray.length;
    }
    public boolean FindKey(String key){
        int hashVal=hashFunc(key);
        while(hashArray[hashVal] != null){
            if (hashArray[hashVal].getKey().equals(key)) {
                return true;
            }
            ++hashVal;
            hashVal %= size;
        }
        return false;
    }
    public String getValueFromKeyFinded(String Key){
        int hashVal=hashFunc(Key);
        while(hashArray[hashVal] != null){
            if (hashArray[hashVal].getKey().equals(Key)) {
                return hashArray[hashVal].getValue();
            }
            ++hashVal;
            hashVal %= size;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btCari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btCari1 = new javax.swing.JButton();
        btCari2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(78, 205, 196));

        Exit.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        Minimize.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Minimize.setText("_");
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setText("Dictionary Of Computer Science Terms");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Minimize)
                .addGap(18, 18, 18)
                .addComponent(Exit)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Minimize)
                    .addComponent(Exit))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(149, 165, 166));

        btCari.setBackground(new java.awt.Color(0, 181, 204));
        btCari.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btCari.setText("Find");
        btCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCariMouseClicked(evt);
            }
        });
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel4.setText("Enter Word      :");

        txtCari.setBackground(new java.awt.Color(197, 239, 247));
        txtCari.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel5.setText("Result            :");

        txtResult.setBackground(new java.awt.Color(197, 239, 247));
        txtResult.setColumns(20);
        txtResult.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        btCari1.setBackground(new java.awt.Color(0, 181, 204));
        btCari1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btCari1.setText("Reset");
        btCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCari1ActionPerformed(evt);
            }
        });

        btCari2.setBackground(new java.awt.Color(0, 181, 204));
        btCari2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btCari2.setText("End");
        btCari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCari2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btCari1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCari2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCari))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCari1)
                    .addComponent(btCari2))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void btCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btCariMouseClicked

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
         String inputan=txtCari.getText();
         Kamus_Versi_English kata=new Kamus_Versi_English(250);
         kata.insert("Application Binary Interface", inputan +": Exposure to hardware specifications and operating systems currently in use");
         kata.insert("Access", inputan +": Activities to retrieve or save data from or to the memory to the disk drive");
         kata.insert("Accessibillity", inputan +": How to set buttons, sounds, views and so on in Windows operating systems");
         kata.insert("Access Method", inputan +": Software that controls the transfer of data between the main storage and input and output equipment in a system");
         kata.insert("Access Time", inputan +": The time it takes to take or enter data from or to Memory");
         kata.insert("Accessories", inputan +": On Windows operating systems, accessories are programs such as Calculator, Notepad, Wordpad, Paint and so on. ");
         kata.insert("Accumulator", inputan +": Part of the arithmatic unit about a computer to store the results of a temporary calculation or some other operation.");
         kata.insert("Acknowledge", inputan +": Sign from the recipient terminal that the sending message has reached without any offense. Acknowledge comes from Acknowledgement words.");
         kata.insert("Accoustic Coupler", inputan +": A tool similar to a simple modem to send computer data through the telephone line. This tool converts binary signals into acoustic signals for acceptable phone microphones, the acoustic signal from the phone speakers will be converted into digital signals.");
         kata.insert("ACL", inputan +"(Access Control Unit) : The method to selectively restrict the use of a service is to make a list of services that can be accessed or that are not allowed by a particular host. ");
         kata.insert("ACPI", inputan +"(Advanced Configuration Power Interface) : A technology that allows the operating system to control the amount of electrical power used by each device installed on the computer.");
         kata.insert("Active Task Button", inputan +": A command button located on the taskbar that will appear if a command must be executed.");
         kata.insert("Active", inputan +": Everything that relates to every tool or system is currently in use.");
         kata.insert("ActiveX", inputan +": The programming environment performed by Microsoft to create an active system on Web pages, which also supports Java, JavaScript, Visual Basic and other programming languages that are all limited and can only be used in Internet Explorer.");
         kata.insert("ADC", inputan +"(Analog/Digital Converter) : The tool used to convert the analog signal into a digital signal.");
         kata.insert("Add-in", inputan +": Additional equipment paired to one of the available boards. Supporting programs are added to an application program.");
         kata.insert("Address", inputan +": The numbers that indicate the location in the memory as the place of information is stored.");
         kata.insert("Adobe PageMaker", inputan +": Application software that processes data for the needs of creation of book layout design, cover for magazines, newspapers, etc. Usually used by the type of computer setting business for the purpose of making invitation cards, business cards, greeting cards, letterhead, and so forth.");
         kata.insert("Adobe Photoshop", inputan +": Application software that processes image and graphics data for printing needs, graphic design.");
         kata.insert("ADSL", inputan +"(Asymmetric Digital Subscriber Lines) : High-level digital data delivery above the line of the phone.");
         kata.insert("Advertiser", inputan +": The same means with merchants, i.e. merchants or companies that give commissions.");
         kata.insert("Affiliate Site", inputan +": Pages where merchant ads are included. We can insert a merchant ad into any page on the website, and the location can be checked in place.");
         kata.insert("AGP", inputan +": (Accelerated Graphics Port) : A high-speed graphics bus that directly connects a graphics card with the main memory. AGP operates independently and separately with PCI buses and generally runs at 66MHz i.e. twice the PCI speed running at 33MHz. AGP 1x performs one-time transfer per working cycle to perform maximum data transfer of 266 MB per second. AGP 2x performs twice the transfer of data per one work cycle of 533 MB per second while AGP 4x performs four times the transfer per one work cycle of 1.06 GB per second. While the maximum data transfer rate on PCI is 132 MB per second.");
         kata.insert("AI", inputan +"(Artificial Intelligence) : The science that develops the computer so that it can work and think and make decisions like human beings.");
         kata.insert("ALGOL", inputan +"(Algortihmic Oriented Language) : A high-level programming language used to resolve issues in limited measures. Generally to make science programs");
         kata.insert("Aligment", inputan +": In computer networks is the process of leveling the components of a system against other components. For example synchronize computer time from a system.");
         kata.insert("Align", inputan +": From the word alignment, that is, the command in a word processing program to flatten a script, whether left, right, or center align.");
         kata.insert("Allocate", inputan +": Instructions for putting a portion of the computer's memory or other units under computer program control.");
         kata.insert("Alpha Numeric", inputan +": A mixture of characters and numbers including letters (A-Z; A-Z), punctuation marks and some special characters e.g. @, #, $, *, etc.");
         kata.insert("Alias", inputan +": The second name of a file, generally the second name is shorter and easier to remember than the first name.");
         kata.insert("ALOHA", inputan +": Intermediate level access surveillance technique for transmission media that handles a lot of access. Data transmission will be done at any time by a station. The shipment will be repeated when you get NAK response (there is a shipment error) from the destination station.");
         kata.insert("Alt Key", inputan +": The button name on the keyboard is located to the right and left of the space bar. This new button works when pressed together with another key. In Windows environment, this button along with certain letters can be used to quickly open and select commands on the menu.");
         kata.insert("ALU", inputan +": (Arithmetic and Logical Unit) :The part of the CPU is useful for processing the data logically and also the data that requires calculations. ALU consists of a register-register to store information.");
         kata.insert("AMD760", inputan +": The AMD760 chipset is an AMD chipset for Athlon processors.");
         kata.insert("Analog", inputan +": The form of electronic communication that uses continuous electromagnetic waves, such as television and radio.");
         kata.insert("Analog Sinyal", inputan +": The continuous electromagnetic waves, having the ability to be transmitted through various media and the range is much larger than the digital signal");
         kata.insert("AND", inputan +": One of the logical operators of the Boolean algebra to compare whether two variables would produce the correct value (1) or False (0)");
         kata.insert("Anti Virus", inputan +": A Program created specifically to detect files in a drive is exposed to viruses or not. This Program also removes the virus.");
         kata.insert("Application Program", inputan +": Computer programs are created to work on or solve specific problems, such as payroll programs.");
         kata.insert("ARPANET", inputan +": The computer network developed with the help of the Advanced Research Project Agency, is the forerunner of the Internet.");
         kata.insert("Assembler", inputan +": Program that serves to convert the program with the Assembly language into the machine language.");
         kata.insert("Assembly", inputan +": The translation process of the program is written with the symbol programming language into the machine language.");
         kata.insert("Assembly Language", inputan +": A low-level programming language that resembles a machine language in a memorable form.");
         kata.insert("Background", inputan +": Colors or drawings are arranged to create a background effect within a webpage.");
         kata.insert("Backplane", inputan +": a board to which the main circuit boards of a computer may be connected, and which provides connections between them.");
         kata.insert("Backspace", inputan +": The keyboard button is located above the Enter key. Function to delete the character saut before the current cursor.");
         kata.insert("Backup", inputan +": A copy of the program file or data file is created to guarantee that the existing data is not lost or deleted if something happens to the original file.");
         kata.insert("Bandwith", inputan +": The capacity of transmsides of electronic connections such as communication networks, I bus computers and computer channels. Usual denoted by bits per second or Hertz. ");
         kata.insert("Banner", inputan +": The parts are not moving in the Web document even though we rolled the the is to the end of the document. Now this is only Ineternet Explorer that supports command banners.");
         kata.insert("Bar Code", inputan +": Numeric characters are displayed in the form of beams with varying thickness.");
         kata.insert("Baterai CMOS", inputan +": This battery serves to power the motherboard in recognizing the configuration installed, when it is not or not yet get power from the power supply.");
         kata.insert("Baud", inputan +": The Signal speed unit is Digita, the limit used to indicate the level of data transmission speed. Typically calculated in bits per second.");
         kata.insert("Binary", inputan +": The numbering system used by the computer consists of only two digits, namely 1 and 0. This is due to the electronic circuits that the computer uses only have two statuses on and off.");
         kata.insert("BIOS", inputan +"(Basic Input Output System) : 1. Part of the operating system that can identify the set of programs used to boot the computer, before placing the system diskette. The BIOS is in ROM (Read Only Memory) of the system and is generally permanently stored. 2. Program used microprocessors to start the computer. The BIOS also regulates the flow of data between the computer operating system and enhancements connected to the computer.");
         kata.insert("Bipolar", inputan +": Refers to a regular transistor or IC as opposed to the MOS and CMOS components.");
         kata.insert("Bit", inputan +": The smallest Unit of information. One bit is enough to declare the difference between yes and no, top and bottom, on and off, one and zero. The computer should display the information in bits because the electronic circuits created only have two circumstances, on or off.");
         kata.insert("Black Box", inputan +": A tool or a process that is specific only within the limits of the input and output process. We do not know what is happening inside.");
         kata.insert("Black Hat", inputan +": Malicious hacker, Black Hat Hacker is also commonly referred to as \"aka crackers\" with the ability to steal data or damage the system that exists in the victim's computer. The advantage of Black hat is the ability to eliminate traces until it is not trackable who actually perpetrators of attacks that occur after their specific objectives are fulfilled.");
         kata.insert("Bluetooth", inputan +": Technology created for close-up wireless connections (RADIUS 10 meters). This technology uses transceiver chips that are assembled on mobile computers, phones, and other portable equipment");
         kata.insert("Brainware", inputan +": Term to declare human being a computer user. Brainware can be categorized into a system of analysts, programmers and operators.");
         kata.insert("Break", inputan +": Command to stop the program. Usually this command is done by cutting the CTRL + C key.");
         kata.insert("Break Point", inputan +": Some computers have a switch that will make the computer stop at a certain point in the program, so the operator can inspect the program's path; Or can also by way of placing stop orders in the program. This command can be deleted if the program has been running properly.");
         kata.insert("Buffer", inputan +": Temporary data storage place. It is often used when data transmission should take place at different speeds");
         kata.insert("Bridge", inputan +": Devices that connect the network physically by holding two LANS using similar protocols");
         kata.insert("Broadcast", inputan +": Delivery of messages to all points in a network.");
         kata.insert("Browse", inputan +": Commands in Windows environment to display disk contents. Application Program used for browsing.");
         kata.insert("Browsing", inputan +": Multiple site browsing activity on the Internet.");
         kata.insert("Bytes", inputan +": Information with a length of 8 bits.");
         kata.insert("BYTE Mode", inputan +": The data delivery Model is done by transferring bytes by Byte.");
         kata.insert("Cache", inputan +": Derived from the word cash, used to increase data transfer speeds either temporarily or permanently.");
         kata.insert("Cancel", inputan +": Used to cancel the order or foil the activity in progress.");
         kata.insert("CAPS Lock", inputan +": A button on the keyboard that works converts all the letter keys to uppercase.");
         kata.insert("Caption", inputan +": In an Ms-Word word processing environment This command is used to add captions to an image, table or other object.");
         kata.insert("Catalog", inputan +": The command in DOS to display a list of files that are in a disk.");
         kata.insert("CD", inputan +"(Carrier Detect) : Modem Status If it is connected with another modem.");
         kata.insert("CD Drive", inputan +"(Drive CD) : A drive to record or play Compact Disk, which is often encountered are CD-ROMS (DISC Read Only Memory) MO (Magneto-Optical) and WORM (Write Once Read Many).");
         kata.insert("CD ROM", inputan +": (Compact Disc Read Only Memory) : Compact Disk that cannot be used for rewriting (removed or added); Used in computer data storage.");
         kata.insert("CD RW", inputan +": A Compact Disk that, in addition to being readable, can also be used to store data by writing it using the CD-RW Drive");
         kata.insert("CD Title", inputan +": Compact Disc that contains computer programs.");
         kata.insert("CDMA", inputan +": (Code Division Multiple Access) : Air-spectrum spread interface technology used on some phones and other wireless networks.");
         kata.insert("Chace", inputan +": Mentions for graphics cards such as VGA card.");
         kata.insert("Chaining", inputan +": The working process of the computer is connected in a series of segments. If a program is too large in memory, the program should be written in several segments. The computer will work in one segment at any one time until completion, the result will be taken to the next segment. So on until the program finishes processing.");
         kata.insert("Channel", inputan +": Channels to transmit electromagnetic signals capable of connecting the CPU with other equipment.");
         kata.insert("Chat", inputan +": Online conversation services commonly used by Internet users to talk to other users");
         kata.insert("CHDIR", inputan +": Command to move or activate the directory in the DOS operating system environment.");
         kata.insert("CHIP", inputan +": Small bits of silicon are the essence of an IC (Integrated Circuit) or a designation for IC.");
         kata.insert("Chipset", inputan +": Chips or chipsets are small pieces of silicon used to store information and computer instruction. Each computer component has at least a chip in it. The Chipset on the motherboard controls the basic input and output (inputs and outputs) of the computer. The Chipset on the video card controls the rendering of the 3D graphics and outputs of the image on your monitor. CPU is one of the very important chip examples. Chipset motherboard eg BX, i810, i820, and many others.");
         kata.insert("Circuit Board", inputan +": A circuit board complete with electronic components that are placed and soldered in place.");
         kata.insert("Click", inputan +": Terms to represent the selection of objects or menus by pressing one mouse button.");
         kata.insert("Client", inputan +": On the network, a client is an application software that allows users to access service or services from a server computer.");
         kata.insert("Client-Server", inputan +": A form of architecture where the client is a receiving device that will display the user interface and run applications (computers) and servers is a device that provides and acts as an application manager, data and security (server or mainframe).");
         kata.insert("Data", inputan +": A collection of numbers and characters that have no meaning. Data can be processed, resulting in information.");
         kata.insert("Database", inputan +": A bunch of interrelated files and forming a data build up. The minimal Database consists of a single file enough to be manipulated by the computer in such a way.");
         kata.insert("Database Administrator", inputan +": The person in charge of defining the pattern of the database structure, specifying the access and storage methods, is authorized to permit accessing the data on the user, and so forth.");
         kata.insert("Database Information Utility", inputan +": Database Information Utility");
         kata.insert("Database Management", inputan +": Data management in a database, how to enter the data in databases, renew it and present information from that data.");
         kata.insert("Decision Support System", inputan +": One computer-based information system that presents information specifically for management to support decision making.");
         kata.insert("Declaration", inputan +": The process of introducing a variable data type to the compiler will therefore be known how much memory to set up for each variable.");
         kata.insert("DECnet", inputan +": A group of network protocols created by Digital Equipment Corporation that are specifically used on DEC's computers to communicate.");
         kata.insert("DECNET", inputan +": Special networking Software for digital computers similar to OSI. DECNET has the ability to be part of a network that uses standard X. 25 or IBM SNA.");
         kata.insert("DECnet/OSI", inputan +": The DECnet protocol is compatible with phase V Digital Network Architecture (DNA) products. This Protocol supports an OSI open system.");
         kata.insert("Decreament", inputan +": To reduce the value of a variable one by one.");
         kata.insert("Decompress", inputan +": Restores the compressed files to their original state of the file.");
         kata.insert("Default", inputan +": Fixed tuning results for running a program or application");
         kata.insert("Demodulation", inputan +": The process of converting analogue signals into digital form.");
         kata.insert("Desktop", inputan +": One computer packaging model that was deliberately designed to be placed on a working desk.");
         kata.insert("Desktop Publishing", inputan +": The Software is used to create and manage formats on magazine and book printing easily. Examples of DTP software are Ventura and Pagemaker.");
         kata.insert("Dial", inputan +": The process of connecting a computer to a station or an Internet address through a communication channel.");
         kata.insert("Dial Line", inputan +": Another term to mention the Channel liaison (switch connection).");
         kata.insert("Dial Up", inputan +": A type of communication that uses a modem and a regular telephone line to be able to connect between computers with another computer, or it can also mean an Internet provider that utilizes the phone line as its main channel. This relationship is only temporary.");
         kata.insert("Dial Up Line", inputan +": Communication line used on dial up process, especially general network or ordinary telephone network.");
         kata.insert("DIR", inputan +": In DOS operating system means the command to display the list of all files in the active disk to the screen.");
         kata.insert("Dial Up Terminal", inputan +": A terminal on the shifting channel.");
         kata.insert("Disconnect", inputan +": The term to declare a disconnection with the communication channel or the state is not connected to any network.");
         kata.insert("Disconnect time-out", inputan +": The deadline used by switched networks to perform termination of communication if a station is inactive exceeds the deadline.");
         kata.insert("Discreate Circuitry", inputan +": Build electronic circuits by attaching multiple parts individually. The inverse of IC, and currently discreate circuitry is rarely used because it is expensive and less reliable.");
         kata.insert("Disk", inputan +": Thin disc coated with magnetic material (iron oxide) capable of storing a certain amount of data or information. Reading and writing information is centered on the track.");
         kata.insert("Disk Cleaner", inputan +": Diskette that cleans the head of a disk drive");
         kata.insert("Diskcopy", inputan +": Program under DOS that serves to copy the entire contents of a disk with the same type of drive.");
         kata.insert("Disk Drive", inputan +": An additional tool is used to place the magnetic disc, rotate the disc and move the read/write head at the desired position when accessing the information from within the disk");
         kata.insert("Diskette", inputan +": The magnetic disc is thin, flexible and wrapped in a box-shaped packaging of plastic material, used to store a certain amount of data/information. The floppy is generally 31/2 inches.");
         kata.insert("Display", inputan +": Hardware that presents the results of computer output in visual form.");
         kata.insert("Documentation", inputan +": Documentation that stores the written description of a program including the program name, program functions, required inputs/outputs, is likely written in the algorithm, how the data structure, and so on.");
         kata.insert("Domain", inputan +": The definition of an address on the Internet, which also refers to a country where the website is used. For example co.id for Indonesia. While co or COM for commercial institutions and net for Internet-related agencies.");
         kata.insert("Domain Name", inputan +": Part of the URL or site address indicating ownership, e.g. andinomaseleno.com indicates the address is owned by Andinomaseleno.");
         kata.insert("Drag", inputan +": Terms that illustrate the activity of moving the mouse while still holding the mouse button");
         kata.insert("Drag and Drop", inputan +": The term describing the activity selects an object and moves the mouse to a new location while still pressing the left mouse button (drag), then placing the object at that location (drop).");
         kata.insert("Duplex", inputan +": 1. Communication lines capable of sending two-way data. 2. Computer system that uses 2 interconnected CPUS.");
         kata.insert("Duplexed System", inputan +": The data communication environment is a system that has two different tools and does not affect each other. Each tool is capable of carrying out its functions; It is possible that one of the tools will be considered a backup.");
         kata.insert("EFT", inputan +"(Electronic Funds Transfer) : The engineering of electronic data transfer or exchange of financial transactions.");
         kata.insert("Eject", inputan +": The command is given on the printer to place the paper at the beginning of the page. If the paper position is in the middle, the rest of the page will be ignored and put the next paper at the beginning of the page.");
         kata.insert("E-mail", inputan +": Internet correspondence. Users can exchange news. The news will be collected in a file for mailbox addressing, so that the user can read the news addressed to him at any time.");
         kata.insert("E-mail Address", inputan +": The address used in the e-mail delivery process to the destination. The address is based on DNS.");
         kata.insert("E-mail Virus", inputan +": The virus that is sent as an attachment file on the e-mail, the new virus will work and infect if we open the attachment file. Most of these are Macro viruses that attack Microsoft Word applications, usually those virus files have an extension of. exe. Examples are like Worm. ExploreZip virus.");
         kata.insert("Encode", inputan +": The activity prepares a program routine into the machine language so that it can be immediately implemented by the computer.");
         kata.insert("Encoder", inputan +": A computer system or network system capable of receiving only one input, each input will generate several combinations of output results.");
         kata.insert("Encryption", inputan +": Translating data into secret codes. Encryption is the most effective way to gain data security. To read the encrypted file, we need to have access to a password that allows us to decrypt the message. Unencapsulation Data is called Plain text, while the ones that are encapsulation are  called cipher text.");
         kata.insert("End", inputan +": Keys on the keyboard, serve to move the cursor to the end of the line.");
         kata.insert("Error", inputan +": The term to indicate that there is a deviation in software or hardware malfunction");
         kata.insert("Ethernet", inputan +": A standard LAN includes cable and communication protocol schemes developed by Xerox Corporation. Now Ethernet is a protocol that is widely used and adapted by other companies.");
         kata.insert("Ethernet Cabel", inputan +": All media cables for the Ethernet network. Example of Ethernet cable is type cable 10base5, UTP/STP");
         kata.insert("Ethernet Meltdown", inputan +": Events that cause saturation in the Ethernet, caused by the inclusion of unofficial data packets. This event only lasts a short time.");
         kata.insert("Ether Talk", inputan +": The encapsulated AppleTalk packages that are passed on the Ethernet cable.");
         kata.insert("Eudora", inputan +": The E-mail Service Application Program on the Internet. Facsimile: The sender tool of the document or the image from one place to another by using the telephone line. Delivery can be done if the sender and receiver both activate this machine.");
         kata.insert("Fading", inputan +": Disruption of transmission lines, especially in the microwave system when signals sent through various lines to the receiver are changed due to atmospheric conditions.");
         kata.insert("Failure", inputan +": A statement indicating that the related tool is not running properly.");
         kata.insert("Female Connector", inputan +": A plug or socket that has a receptacles. The opponent is a \"man connector\" that has a pin");
         kata.insert("Fetch", inputan +": Software Program to move files developed by Dartmouth College for Macintosh. The Program provides access to a user friendly FTP.");
         kata.insert("File", inputan +": The File consists of a set of interconnected records. Each record has a number that is adjusted to its position in the file.");
         kata.insert("Folder", inputan +": In a Graphical User Interface (GUI) environment such as Windows and Macintosh, a folder is an object that can contain multiple documents. Folders are used to organize information. On DOS and UNIX, the folder is called Directory (directory).");
         kata.insert("Gigabyte", inputan +": A term to mention an image that has a gray color, a.k.a. black and white. Greyscale represents the number of colors (from Gray, to black – white) that are in a single image. The bigger the Grayscale figure, the formed image is closer to reality.");
         kata.insert("Gigacycle", inputan +": Unit of frequency measure with 1 Gigacycle = 1 billion Hertz.");
         kata.insert("Google", inputan +": Name of search engine on Internet.");
         kata.insert("Glossary", inputan +": The following glossary describes the meaning of the terms.");
         kata.insert("Gopher", inputan +": A menu-based information system on the Internet is popular for its ability to relate to other gopher sites in the same menu.");
         kata.insert("GPRS", inputan +"(General Packet Radio Service ) :\n" +"Package-based communication services, wirelessly as a communication medium. This service is for portable computers (notebooks). The basis of GPRS is GSM (Global System for Mobile Communication) communication. The speeds offered range from 56 Kbps to 114 Kbps, allowing for faster access to the Internet.");
         kata.insert("GSM", inputan +"(Global System for Mobile Communication) : Cellular digital or PCS standards used around the world. GSM is the most widely used standard in Europe and southeast Asia.");
         kata.insert("Guestbook", inputan +": Interactive facilities in a webpage that allow visitors to write messages.");
         kata.insert("Homepage", inputan +": The first page of a Web Site.");
         kata.insert("Host", inputan +": A term used to designate a computer that allows its users to connect to the Internet.");
         kata.insert("Host Name", inputan +": The name of the computer within the Internet, is used to indicate the URL naming scheme.");
         kata.insert("HTTP (Hyper Text Transfer Protocol)", inputan +": A method or protocol to download files to a computer. This protocol is based on hyper text, a text format commonly used on the Internet.");
         kata.insert("Icon", inputan +": Interlaced GIP : A special GIF type that allows the display of the image to be displayed little by little when a webpage is being downloaded.");
         kata.insert("Internet", inputan +": A general term used to designate a world-wide Network consisting of computers and service services or about 30 to 50 million computer users and dozens of information systems including e-mail, Gopher, FTP and the World Wide Web.");
         kata.insert("Internet Device", inputan +": Advanced tools such as computers used to be able to communicate or interact through the Internet, whether to surf, send and receive e-mails, even to chat, using text, sound, images or video, for example: Notebook, palmtop, handphone, Internet-TV.");
         kata.insert("Internet Explorer", inputan +": A well-known free Web browser produced by Microsoft.");
         kata.insert("Intranet", inputan +": Information resources are used for the internal interests of an agency or company using an existing computer network.");
         kata.insert("Java", inputan +": The programming language to create active content within a Web page, can also be run on all computers. Java applets are retrieved/accessed from Web pages and run in total.");
         kata.insert("JavaScript", inputan +": Language script interpreter to create an active content in a Web page.");
         kata.insert("JPEG (Joint Photographic Expert Group) :", inputan +": File formats that contain data in the form of images. JPEG images are compressed in lossy, so the image quality is lowered to obtain a small file size. However, the difference in quality will not be noticeable for certain images. JPEG is usually used for images of obscure color boundaries, such as photos, paintings, etc.");
         kata.insert("Kbps", inputan +": The unit of byte is equal to 1000 bits per second.");
         kata.insert("KHz", inputan +": The unit of frequency is equal to 1000 cycles per second.");
         kata.insert("Konektor Power", inputan +": Pin that connects the motherboard with the power supply in the case of a computer. On the AT type motherboard, the casing required is an AT type as well. The Type AT Power connectorconsists of two parts, where two cables from the power supply will be stuck. In the ATX type, the power supply cable is integrated into one intact header so that it stays on the motherboard. This cable consists of two columns according to the PIN on the motherboard consisting of two arrays of pins as well. There are several motherboards that provide two types of power, AT and ATX connectors. Most new motherboards already have ATX type.");
         kata.insert("LAN", inputan +": A network that is built on a location like at home or office buildings. It can also be interpreted as a computer communication system that is limited to no more than a few kilometers and uses a high-speed connection between 2 and 100 Mbps.");
         kata.insert("Layer", inputan +": Layer (concept) in networking. Various communication models such as OSI and TCP/IP consist of several layers that compose the protocol.");
         kata.insert("LCD (Liquid Crystal Display)", inputan +": The type of screen display using liquid compounding that has a polar molecular structure, flanked between two transparent electrodes. When the electric field is given, the molecule adjusts its position on the terrain, forming a crystalline arrangement that polarizes light through it.");
         kata.insert("LED (Light Emitting Diode)", inputan +": A small lamp is used as a marker or pointer.");
         kata.insert("Link", inputan +": Connection or connection from a source to another source. For example in networking or Internet systems.");
         kata.insert("Listsery", inputan +": Mailing list management Software.");
         kata.insert("Load Time", inputan +": The time it takes to fetch/open a web page on the computer.");
         kata.insert("Locate", inputan +": Commands are used in Linux/Unix to obtain certain files. Only the locate command should be preceded by slocate to do updating the file information within that host.");
         kata.insert("Localhost", inputan +": In the Networking world, Localhost is the term used for the host itself. The name localhost is used for the application configuration before actually getting the hostname of its hostmaster.");
         kata.insert("Log", inputan +": Records that record all activities of an application are executed. Sometimes Log is also used to analyze the status of an application.");
         kata.insert("Login", inputan +": The process to enter into a servicesonline containing the name and password");
         kata.insert("Logout", inputan +": Exit or close, the same means by signing out. Multiuser Systemany computer system that can be used by more than one person.");
         kata.insert("Modem", inputan +": Short for modulator/demodulator; Communication tool that allows the computer to transmit information through the standard telephone line");
         kata.insert("Motherboard", inputan +": The largest component in the PC. Called ' mother ' because this board is home to all PC components such as processors, main memory, support networks and bus controllers.");
         kata.insert("MPEG Card", inputan +": Short for Motion Picture Expert Group. The card that completes the CD-ROM to be able to display the full motion video smoothly, one full motion video must be run at a speed of 30 frames per second (fps). By installing MPEG card and CD-ROM drive on the PC, we can watch CD or karaoke movies on PC.");
         kata.insert("MMX/ Microprocessor Multimedia Exstensions", inputan +": A new generation Pentium processor that can boost multimedia and communication performance up to 60% above the Pentium. In general MMX makes games/games more realistic, better videos and the facility of charts more perfect.");
         kata.insert("Offline", inputan +": A Status where a device cannot communicate with or is controlled by a computer.");
         kata.insert("Online", inputan +": Active and ready for operation, can communicate with or controlled by the computer.");
         kata.insert("Postcript Page Description Language", inputan +": A programming language dedicated to defining the look of a document, usually providing flexible font capability and high-quality graphics.");
         kata.insert("Plotter", inputan +": Tools for drawing graphs, diagrams and other line graphs using a pen or electrostatic charge and toner.");
         kata.insert("Pentium", inputan +": The designation for Intel 80586 processors is also called P5. The Pentium processor is based on 64-bit operations and has 3.1 million transistors.");
         kata.insert("Pentium Pro", inputan +": The designation for Intel 80686 processors is also called P6. It is a 64-bit operation-based processor and has 5.5 million transistors. The target market is generally for networked computers with the Windows NT (New Technology) operating system.");
         kata.insert("Peripheral", inputan +": The term in the computer is used for equipment such as a brushed drive, printer, modem and other devices that are connected to the computer and controlled by the processor.");
         kata.insert("Prosesor", inputan +": It is also known as a single Chip center processing unit, which means translating and carrying out instruction-instructions through it, or a tool that functions as a computer brain.");
         kata.insert("Pixel/ Picture element", inputan +": The smallest elements are displayed or printed that can be handled by hardware and software to form letters, numbers or graphs. Or a grid point consisting of thousands of points one by one to form an image on the screen by a computer or on printer paper.");
         kata.insert("Port", inputan +": Sockets, a type of outlet on computer hardware, are also called input/output connectors; is the place to pass data in and out of the computing tool via cable.");
         kata.insert("Power Supply", inputan +": Tools that convert electricity from electrical sockets to lower voltages (especially 5 to 12 volts DC) are required by computer systems.");
         kata.insert("Query", inputan +": The process of retrieving data from a data base and providing it for use or a specific set of instructions to retrieve certain data on a recurring basis.");
         kata.insert("Real time", inputan +": Real time operation is an environment in which the activity of the machine matches the human perception of the time or where the operation of the computer runs at a speed with physical or external processes.");
         kata.insert("Resolution/ Resolusi", inputan +": The clarity or smoothness of details obtained by the monitor or printer in generating images. Resolution is usually used to show the total number of pixels displayed horizontally or vertically in the video view.");
         kata.insert("Router", inputan +": An intermediate tool on the communication network that launches message delivery.");
         kata.insert("Scan", inputan +": Moving the light-sensitive tools along the surface occupied images such as text pages, converting various fields on the surface into binary digits that can be interpretation by the computer.");
         kata.insert("Spreadsheet program", inputan +": Computer program packages used to process financial data and other data related to numbers such as budgets, cash flow analysis, and so on.");
         kata.insert("Shareware", inputan +": Programs that can be used on a limited basis for a particular trial period.");
         kata.insert("SRAM/ Static RAM", inputan +": The RAM chip can store about a quarter of data on the DRAM chip but is much faster than the DRAM. The price is still expensive.");
         kata.insert("Stack", inputan +": A reserved memory area where the program stores status data, such as procedures and functions that call return addresses, pass parameters, and (occasionally) a local variable.");
         kata.insert("Storage", inputan +": A tool that can physically be used to store data or information about files/archives and computer readable.");
         kata.insert("SIMM", inputan +": Abbreviation of Single In-line Memory Module. A small network board designed to occupy memory chip/IC.");
         kata.insert("SCSI/Small Computer System Interface", inputan +": High speed Paralet Interface that is used to connect the computer to other alata such as hard disk, printer, or to other computer network.");
         kata.insert("Serial port", inputan +": Connectors/sockets for input/output locations for serial data transmissions such as printers or mice.");
         kata.insert("Sound clip", inputan +": The Sound collection on a disk can be retrieved and incorporated into the document with the help of certain software or hardware.");
         kata.insert("Token Ring", inputan +":  A unique data object structure or message that travels between the nodes of a network that is masked by a bracelet (closed topology, ring) and describes the status of the network.");
         kata.insert("Universal Serial Bus/ USB", inputan +": The combination of hardware, software and power cord that generates a way of communicating between all the different parts of the computer universally, one by one.");
         kata.insert("Validasi", inputan +": Testing to measure compliance with standards.");
         kata.insert("Visual Image", inputan +": Descriptions of images are stored and recorded in various ways and are an edited copy or reproduction for an image on a computer.");
         kata.insert("Video Card", inputan +": Card that converts analog data from the camera, VCR, laser disc, or television into digital data, so it can be stored on the hard drive. The video data is subsequently processed by the computer and the results can be displayed on the computer screen, the TV plane, or recorded to a video cassett");
         kata.insert("VGA/ Video Graphic Array", inputan +": It is a video adapter introduced by IBM in 1987, which duplicates samples of a physical variable, such as sound. The higher the rate, or the more samples are taken, the more tightly the digitising results resemble the original.");
         kata.insert("Wavetable synthesizer", inputan +": A stand-alone system, generating digital sound that is not due to manipulation of physical tools or sound recordings and can produce realistic sound without interruption.");
         kata.insert("WORM/ Write Once, Read Many", inputan +": Types of optical disks that are able and read repeat but cannot be changed once recorded with high capacity storage space.");
         kata.insert("Worksheet", inputan +": The term used to describe the data files formed and used by and with the electronic spreadsheet program. MS Excel Example");
         kata.insert("Xing MPEG Software", inputan +": Programs that can play MPEG applications in the form of films in CD/Video CD media.");
         kata.insert("ZIP", inputan +": Extension/Connection There is a file name indicating that the file has been compressed by the PKZIP program. Example motor. zip");
         kata.insert("", inputan +": ");
         
         if (kata.FindKey(inputan)) {
            txtResult.setText(kata.getValueFromKeyFinded(inputan));
        }else{
            txtResult.setText(inputan+" tidak ditemukan");
         } 
    }//GEN-LAST:event_btCariActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCari1ActionPerformed
        // TODO add your handling code here:
        txtCari.setText("");
        txtResult.setText("");
    }//GEN-LAST:event_btCari1ActionPerformed

    private void btCari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCari2ActionPerformed
        // TODO add your handling code here:
        Thankyou Ty = new Thankyou();
        Ty.setVisible(true);
        Ty.pack();
        Ty.setLocationRelativeTo(null);
        Ty.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btCari2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kamus_Versi_Bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kamus_Versi_Bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kamus_Versi_Bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kamus_Versi_Bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kamus_Versi_English(200).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Minimize;
    private javax.swing.JButton btCari;
    private javax.swing.JButton btCari1;
    private javax.swing.JButton btCari2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
